/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.spec;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import io.seqera.wave.api.v1.model.BuildStatusResponse;
import io.seqera.wave.api.v1.model.WaveBuildRecord;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Controller
public interface BuildsApiSpec {

    /**
     * Return the conda lock file used during the build.
     *
     * @param id (required)
     * @return The request has succeeded. (status code 200)
     *         or The server cannot find the requested resource. (status code 404)
     */
    @Get("/w1/builds/{id}/condalock")
    String getBuildCondaLock(
        @PathVariable("id") @NotNull String id
    );

    /**
     * Supply build logs identified by the id path variable.
     *
     * @param id (required)
     * @return The request has succeeded. (status code 200)
     *         or The server cannot find the requested resource. (status code 404)
     */
    @Get("/w1/builds/{id}/logs")
    String getBuildLogs(
        @PathVariable("id") @NotNull String id
    );

    /**
     * Provides the record of a build identified by the id path variable.
     *
     * @param id (required)
     * @return The request has succeeded. (status code 200)
     *         or The server cannot find the requested resource. (status code 404)
     */
    @Get("/w1/builds/{id}")
    WaveBuildRecord getBuildRecord(
        @PathVariable("id") @NotNull String id
    );

    /**
     * Provides the status of a build identified by the id path variable.
     *
     * @param id (required)
     * @return The request has succeeded. (status code 200)
     *         or The server cannot find the requested resource. (status code 404)
     */
    @Get("/w1/builds/{id}/status")
    BuildStatusResponse getBuildStatus(
        @PathVariable("id") @NotNull String id
    );

}