/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.spec;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import io.seqera.wave.api.v1.model.ContainerRequest;
import io.seqera.wave.api.v1.model.ContainerResponse;
import io.seqera.wave.api.v1.model.ContainerStatusResponse;
import io.micronaut.http.HttpResponse;
import io.seqera.wave.api.v1.model.WaveContainerRecord;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Controller
public interface ContainersApiSpec {

    /**
     * This endpoint allows you to submit a request to access a private container registry via Wave, or build a container image on-the-fly with a Dockerfile or Conda recipe file and returns the name of the container request made available by Wave.
     *
     * @param containerRequest (required)
     * @return The request has succeeded. (status code 200)
     */
    @Post("/w1/containers")
    ContainerResponse createContainer(
        @Body @NotNull @Valid ContainerRequest containerRequest
    );

    /**
     * Revoke the container token for a request identified by the id path variable.
     *
     * @param id (required)
     * @return There is no content to send for this request, but the headers may be useful.  (status code 204)
     *         or The server cannot find the requested resource. (status code 404)
     */
    @Delete("/w1/containers/{id}")
    HttpResponse<Void> deleteContainer(
        @PathVariable("id") @NotNull String id
    );

    /**
     * This endpoint allows you to get the details of a container request made to Wave.
     *
     * @param id (required)
     * @return The request has succeeded. (status code 200)
     *         or The server cannot find the requested resource. (status code 404)
     */
    @Get("/w1/containers/{id}")
    WaveContainerRecord getContainerDetails(
        @PathVariable("id") @NotNull String id
    );

    /**
     * This endpoint allows you to get the status of a container request made to Wave.
     *
     * @param id (required)
     * @return The request has succeeded. (status code 200)
     *         or The server cannot find the requested resource. (status code 404)
     */
    @Get("/w1/containers/{id}/status")
    ContainerStatusResponse getContainerStatus(
        @PathVariable("id") @NotNull String id
    );

}