/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.spec;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import io.seqera.wave.api.v1.model.ValidateRegistryCredsRequest;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Controller
public interface CredentialsApiSpec {

    /**
     * This endpoint allows you to validate the credentials of a container registry.
     *
     * @param validateRegistryCredsRequest (required)
     * @return The request has succeeded. (status code 200)
     */
    @Post("/w1/credentials/validate")
    Boolean validate(
        @Body @NotNull @Valid ValidateRegistryCredsRequest validateRegistryCredsRequest
    );

}