/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.spec;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import io.micronaut.http.HttpResponse;
import io.seqera.wave.api.v1.model.ScanSubmitRequest;
import io.seqera.wave.api.v1.model.ScanSubmitResponse;
import io.seqera.wave.api.v1.model.WaveScanRecord;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Controller
public interface ScansApiSpec {

    /**
     * This endpoint allows you to get the logs of a container scan request made to Wave.
     *
     * @param id (required)
     * @return The request has succeeded. (status code 200)
     *         or The server cannot find the requested resource. (status code 404)
     */
    @Get("/w1/scans/{id}/logs")
    HttpResponse<@NotNull String> getScanLogs(
        @PathVariable("id") @NotNull String id
    );

    /**
     * Return the SPDX SBOM document for a completed scan identified by the id path variable.
     *
     * @param id (required)
     * @return The request has succeeded. (status code 200)
     *         or The server cannot find the requested resource. (status code 404)
     */
    @Get("/w1/scans/{id}/spdx")
    String getScanSpdx(
        @PathVariable("id") @NotNull String id
    );

    /**
     * This endpoint allows you to get the details of a container scan request made to Wave.
     *
     * @param id (required)
     * @return The request has succeeded. (status code 200)
     *         or The server cannot find the requested resource. (status code 404)
     */
    @Get("/w1/scans/{id}")
    WaveScanRecord scanImage(
        @PathVariable("id") @NotNull String id
    );

    /**
     * Submit a container scan request.
     *
     * @param scanSubmitRequest (required)
     * @return The request has succeeded. (status code 200)
     */
    @Post("/w1/scans")
    ScanSubmitResponse submitScan(
        @Body @NotNull @Valid ScanSubmitRequest scanSubmitRequest
    );

}