FROM {{base_image}}
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends {{base_packages}} {{target}} \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
