# Config for pre-commit: https://pre-commit.com/
---
minimum_pre_commit_version: "2.9.2"
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
