services:
  wave:
    image: wave-app # replace with the actual image name
    ports:
      - 9090:9090
    volumes:
      - $PWD:/work
    environment:
      - MICRONAUT_ENVIRONMENTS=lite
      - WAVE_BUILD_WORKSPACE=/work/build-workspace
    working_dir: /work
