jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wave
    username: postgres
    password: postgres
