wave:
  build:
    repo : "195996028523.dkr.ecr.eu-west-1.amazonaws.com/wave/build/dev"
    cache : "195996028523.dkr.ecr.eu-west-1.amazonaws.com/wave/build/cache"
    public-repo : "community.wave.seqera.io"
