---
rate-limit:
  build:
    anonymous: 10/1h
    authenticated: 10/1m
  pull:
    anonymous: 100/1h
    authenticated: 100/1m
  timeout-errors:
    maxRate: 10/2m
  httpRequest:
    timeout-duration : 500ms
    limit-refresh-period : 1s
    limit-for-period : 100
    status-code : 429
---
micronaut:
  caches:
    rate-limiter:
      expire-after-access: 10m
...
