micronaut:
  metrics:
    enabled: true
    export :
      prometheus :
        enabled : true
        step : PT1M
        descriptions : true
    binders:
      web:
        server:
          percentiles: "0.95,0.99"
        client:
          percentiles: "0.95,0.99"
      netty:
        queues:
          enabled: true
        bytebuf-allocators:
          enabled: true
        channels:
          enabled: true
endpoints:
  prometheus:
    sensitive: false
