wave:
  db:
    uri: "jdbc:postgresql://localhost:5432/wave"
    user: "postgres"
    password: "postgres"
datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    url: "${wave.db.uri}"
    username: "${wave.db.user}"
    password: "${wave.db.password}"

