name: 'Deploy to cluster'
inputs:
  app:
    required: true
    type: string
  container:
    required: true
    type: string
  namespace:
    required: true
    type: string
  aws-access-key-id:
    required: true
    type: string
  aws-secret-access-key:
    required: true
    type: string
  aws-region:
    required: true
    type: string
  kube-config-data:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Deploy to prod
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ inputs.kube-config-data }}
      with:
        args: set image deployment/${{inputs.app}} ${{inputs.app}}=${{inputs.container}}:$(cat VERSION) -n ${{inputs.namespace}}
