/*
 * Wave API
 * Wave Containers Provisioning Service API A comprehensive container orchestration and build service
 *
 * The version of the OpenAPI document: 1.25.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.schema.v0;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Build status response
 */
@Serdeable
@JsonPropertyOrder({
    BuildStatusResponse.JSON_PROPERTY_ID,
    BuildStatusResponse.JSON_PROPERTY_STATUS,
    BuildStatusResponse.JSON_PROPERTY_STATUS_MESSAGE,
    BuildStatusResponse.JSON_PROPERTY_START_TIME,
    BuildStatusResponse.JSON_PROPERTY_COMPLETE_TIME,
    BuildStatusResponse.JSON_PROPERTY_DURATION,
    BuildStatusResponse.JSON_PROPERTY_SUCCEEDED,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class BuildStatusResponse {

    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_STATUS = "status";
    public static final String JSON_PROPERTY_STATUS_MESSAGE = "statusMessage";
    public static final String JSON_PROPERTY_START_TIME = "startTime";
    public static final String JSON_PROPERTY_COMPLETE_TIME = "completeTime";
    public static final String JSON_PROPERTY_DURATION = "duration";
    public static final String JSON_PROPERTY_SUCCEEDED = "succeeded";

    /**
     * Build ID
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String id;

    /**
     * Build status
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String status;

    /**
     * Status message
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_STATUS_MESSAGE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String statusMessage;

    /**
     * Start time
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_START_TIME)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private OffsetDateTime startTime;

    /**
     * Complete time
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_COMPLETE_TIME)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private OffsetDateTime completeTime;

    /**
     * Duration in milliseconds
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_DURATION)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Long duration;

    /**
     * Succeeded flag
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_SUCCEEDED)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Boolean succeeded;

    /**
     * Build ID
     *
     * @return the id property value
     */
    public String getId() {
        return id;
    }

    /**
     * Set the id property value
     *
     * @param id property value to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Set id in a chainable fashion.
     *
     * @return The same instance of BuildStatusResponse for chaining.
     */
    public BuildStatusResponse id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Build status
     *
     * @return the status property value
     */
    public String getStatus() {
        return status;
    }

    /**
     * Set the status property value
     *
     * @param status property value to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Set status in a chainable fashion.
     *
     * @return The same instance of BuildStatusResponse for chaining.
     */
    public BuildStatusResponse status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Status message
     *
     * @return the statusMessage property value
     */
    public String getStatusMessage() {
        return statusMessage;
    }

    /**
     * Set the statusMessage property value
     *
     * @param statusMessage property value to set
     */
    public void setStatusMessage(String statusMessage) {
        this.statusMessage = statusMessage;
    }

    /**
     * Set statusMessage in a chainable fashion.
     *
     * @return The same instance of BuildStatusResponse for chaining.
     */
    public BuildStatusResponse statusMessage(String statusMessage) {
        this.statusMessage = statusMessage;
        return this;
    }

    /**
     * Start time
     *
     * @return the startTime property value
     */
    public OffsetDateTime getStartTime() {
        return startTime;
    }

    /**
     * Set the startTime property value
     *
     * @param startTime property value to set
     */
    public void setStartTime(OffsetDateTime startTime) {
        this.startTime = startTime;
    }

    /**
     * Set startTime in a chainable fashion.
     *
     * @return The same instance of BuildStatusResponse for chaining.
     */
    public BuildStatusResponse startTime(OffsetDateTime startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * Complete time
     *
     * @return the completeTime property value
     */
    public OffsetDateTime getCompleteTime() {
        return completeTime;
    }

    /**
     * Set the completeTime property value
     *
     * @param completeTime property value to set
     */
    public void setCompleteTime(OffsetDateTime completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * Set completeTime in a chainable fashion.
     *
     * @return The same instance of BuildStatusResponse for chaining.
     */
    public BuildStatusResponse completeTime(OffsetDateTime completeTime) {
        this.completeTime = completeTime;
        return this;
    }

    /**
     * Duration in milliseconds
     *
     * @return the duration property value
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * Set the duration property value
     *
     * @param duration property value to set
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * Set duration in a chainable fashion.
     *
     * @return The same instance of BuildStatusResponse for chaining.
     */
    public BuildStatusResponse duration(Long duration) {
        this.duration = duration;
        return this;
    }

    /**
     * Succeeded flag
     *
     * @return the succeeded property value
     */
    public Boolean getSucceeded() {
        return succeeded;
    }

    /**
     * Set the succeeded property value
     *
     * @param succeeded property value to set
     */
    public void setSucceeded(Boolean succeeded) {
        this.succeeded = succeeded;
    }

    /**
     * Set succeeded in a chainable fashion.
     *
     * @return The same instance of BuildStatusResponse for chaining.
     */
    public BuildStatusResponse succeeded(Boolean succeeded) {
        this.succeeded = succeeded;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var buildStatusResponse = (BuildStatusResponse) o;
        return Objects.equals(id, buildStatusResponse.id)
            && Objects.equals(status, buildStatusResponse.status)
            && Objects.equals(statusMessage, buildStatusResponse.statusMessage)
            && Objects.equals(startTime, buildStatusResponse.startTime)
            && Objects.equals(completeTime, buildStatusResponse.completeTime)
            && Objects.equals(duration, buildStatusResponse.duration)
            && Objects.equals(succeeded, buildStatusResponse.succeeded);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, status, statusMessage, startTime, completeTime, duration, succeeded);
    }

    @Override
    public String toString() {
        return "BuildStatusResponse("
            + "id: " + getId() + ", "
            + "status: " + getStatus() + ", "
            + "statusMessage: " + getStatusMessage() + ", "
            + "startTime: " + getStartTime() + ", "
            + "completeTime: " + getCompleteTime() + ", "
            + "duration: " + getDuration() + ", "
            + "succeeded: " + getSucceeded()
            + ")";
    }

}