/*
 * Wave API
 * Wave Containers Provisioning Service API A comprehensive container orchestration and build service
 *
 * The version of the OpenAPI document: 1.25.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.schema.v0;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Error response
 */
@Serdeable
@JsonPropertyOrder({
    ErrorResponse.JSON_PROPERTY_MESSAGE,
    ErrorResponse.JSON_PROPERTY_DETAILS,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ErrorResponse {

    public static final String JSON_PROPERTY_MESSAGE = "message";
    public static final String JSON_PROPERTY_DETAILS = "details";

    /**
     * Error message
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_MESSAGE)
    private String message;

    /**
     * Error details
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_DETAILS)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String details;

    public ErrorResponse(String message) {
        this.message = message;
    }

    /**
     * Error message
     *
     * @return the message property value
     */
    public String getMessage() {
        return message;
    }

    /**
     * Set the message property value
     *
     * @param message property value to set
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Set message in a chainable fashion.
     *
     * @return The same instance of ErrorResponse for chaining.
     */
    public ErrorResponse message(String message) {
        this.message = message;
        return this;
    }

    /**
     * Error details
     *
     * @return the details property value
     */
    public String getDetails() {
        return details;
    }

    /**
     * Set the details property value
     *
     * @param details property value to set
     */
    public void setDetails(String details) {
        this.details = details;
    }

    /**
     * Set details in a chainable fashion.
     *
     * @return The same instance of ErrorResponse for chaining.
     */
    public ErrorResponse details(String details) {
        this.details = details;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var errorResponse = (ErrorResponse) o;
        return Objects.equals(message, errorResponse.message)
            && Objects.equals(details, errorResponse.details);
    }

    @Override
    public int hashCode() {
        return Objects.hash(message, details);
    }

    @Override
    public String toString() {
        return "ErrorResponse("
            + "message: " + getMessage() + ", "
            + "details: " + getDetails()
            + ")";
    }

}