/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Options for Conda environments.
 */
@Serdeable
@JsonPropertyOrder({
    CondaOpts.JSON_PROPERTY_BASE_PACKAGES,
    CondaOpts.JSON_PROPERTY_COMMANDS,
    CondaOpts.JSON_PROPERTY_MAMBA_IMAGE,
    CondaOpts.JSON_PROPERTY_BASE_IMAGE,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class CondaOpts {

    public static final String JSON_PROPERTY_BASE_PACKAGES = "basePackages";
    public static final String JSON_PROPERTY_COMMANDS = "commands";
    public static final String JSON_PROPERTY_MAMBA_IMAGE = "mambaImage";
    public static final String JSON_PROPERTY_BASE_IMAGE = "baseImage";

    /**
     * Names of base packages.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_BASE_PACKAGES)
    private String basePackages;

    /**
     * Command to be included in the container.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_COMMANDS)
    private List<@NotNull String> commands = new ArrayList<>();

    /**
     * Name of the docker image used to build Conda containers.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_MAMBA_IMAGE)
    private String mambaImage;

    /**
     * Base image for the final stage of multi-stage builds.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_BASE_IMAGE)
    private String baseImage;

    /**
     * Names of base packages.
     *
     * @return the basePackages property value
     */
    public String getBasePackages() {
        return basePackages;
    }

    /**
     * Set the basePackages property value
     *
     * @param basePackages property value to set
     */
    public void setBasePackages(String basePackages) {
        this.basePackages = basePackages;
    }

    /**
     * Set basePackages in a chainable fashion.
     *
     * @return The same instance of CondaOpts for chaining.
     */
    public CondaOpts basePackages(String basePackages) {
        this.basePackages = basePackages;
        return this;
    }

    /**
     * Command to be included in the container.
     *
     * @return the commands property value
     */
    public List<@NotNull String> getCommands() {
        return commands;
    }

    /**
     * Set the commands property value
     *
     * @param commands property value to set
     */
    public void setCommands(List<@NotNull String> commands) {
        this.commands = commands;
    }

    /**
     * Set commands in a chainable fashion.
     *
     * @return The same instance of CondaOpts for chaining.
     */
    public CondaOpts commands(List<@NotNull String> commands) {
        this.commands = commands;
        return this;
    }
    /**
     * Add an item to the commands property in a chainable fashion.
     *
     * @return The same instance of CondaOpts for chaining.
     */
    public CondaOpts addCommandsItem(String commandsItem) {
        commands.add(commandsItem);
        return this;
    }

    /**
     * Name of the docker image used to build Conda containers.
     *
     * @return the mambaImage property value
     */
    public String getMambaImage() {
        return mambaImage;
    }

    /**
     * Set the mambaImage property value
     *
     * @param mambaImage property value to set
     */
    public void setMambaImage(String mambaImage) {
        this.mambaImage = mambaImage;
    }

    /**
     * Set mambaImage in a chainable fashion.
     *
     * @return The same instance of CondaOpts for chaining.
     */
    public CondaOpts mambaImage(String mambaImage) {
        this.mambaImage = mambaImage;
        return this;
    }

    /**
     * Base image for the final stage of multi-stage builds.
     *
     * @return the baseImage property value
     */
    public String getBaseImage() {
        return baseImage;
    }

    /**
     * Set the baseImage property value
     *
     * @param baseImage property value to set
     */
    public void setBaseImage(String baseImage) {
        this.baseImage = baseImage;
    }

    /**
     * Set baseImage in a chainable fashion.
     *
     * @return The same instance of CondaOpts for chaining.
     */
    public CondaOpts baseImage(String baseImage) {
        this.baseImage = baseImage;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var condaOpts = (CondaOpts) o;
        return Objects.equals(basePackages, condaOpts.basePackages)
            && Objects.equals(commands, condaOpts.commands)
            && Objects.equals(mambaImage, condaOpts.mambaImage)
            && Objects.equals(baseImage, condaOpts.baseImage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(basePackages, commands, mambaImage, baseImage);
    }

    @Override
    public String toString() {
        return "CondaOpts("
            + "basePackages: " + getBasePackages() + ", "
            + "commands: " + getCommands() + ", "
            + "mambaImage: " + getMambaImage() + ", "
            + "baseImage: " + getBaseImage()
            + ")";
    }

}