/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Request payload for inspecting a container.
 */
@Serdeable
@JsonPropertyOrder({
    ContainerInspectRequest.JSON_PROPERTY_CONTAINER_IMAGE,
    ContainerInspectRequest.JSON_PROPERTY_TOWER_ACCESS_TOKEN,
    ContainerInspectRequest.JSON_PROPERTY_TOWER_ENDPOINT,
    ContainerInspectRequest.JSON_PROPERTY_TOWER_WORKSPACE_ID,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ContainerInspectRequest {

    public static final String JSON_PROPERTY_CONTAINER_IMAGE = "containerImage";
    public static final String JSON_PROPERTY_TOWER_ACCESS_TOKEN = "towerAccessToken";
    public static final String JSON_PROPERTY_TOWER_ENDPOINT = "towerEndpoint";
    public static final String JSON_PROPERTY_TOWER_WORKSPACE_ID = "towerWorkspaceId";

    /**
     * Name of the container to be inspected, e.g., &#x60;docker.io/library/ubuntu:latest&#x60;.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_CONTAINER_IMAGE)
    private String containerImage;

    /**
     * Access token of the user account granting access to the Seqera Platform service specified via &#x60;towerEndpoint&#x60; (optional).
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TOWER_ACCESS_TOKEN)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String towerAccessToken;

    /**
     * Seqera Platform service endpoint from where container registry credentials are retrieved (optional). Default &#x60;https://api.cloud.seqera.io&#x60;.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TOWER_ENDPOINT)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String towerEndpoint;

    /**
     * ID of the Seqera Platform workspace from where the container registry credentials are retrieved (optional). When omitted the personal workspace is used.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TOWER_WORKSPACE_ID)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Long towerWorkspaceId;

    /**
     * Name of the container to be inspected, e.g., &#x60;docker.io/library/ubuntu:latest&#x60;.
     *
     * @return the containerImage property value
     */
    public String getContainerImage() {
        return containerImage;
    }

    /**
     * Set the containerImage property value
     *
     * @param containerImage property value to set
     */
    public void setContainerImage(String containerImage) {
        this.containerImage = containerImage;
    }

    /**
     * Set containerImage in a chainable fashion.
     *
     * @return The same instance of ContainerInspectRequest for chaining.
     */
    public ContainerInspectRequest containerImage(String containerImage) {
        this.containerImage = containerImage;
        return this;
    }

    /**
     * Access token of the user account granting access to the Seqera Platform service specified via &#x60;towerEndpoint&#x60; (optional).
     *
     * @return the towerAccessToken property value
     */
    public String getTowerAccessToken() {
        return towerAccessToken;
    }

    /**
     * Set the towerAccessToken property value
     *
     * @param towerAccessToken property value to set
     */
    public void setTowerAccessToken(String towerAccessToken) {
        this.towerAccessToken = towerAccessToken;
    }

    /**
     * Set towerAccessToken in a chainable fashion.
     *
     * @return The same instance of ContainerInspectRequest for chaining.
     */
    public ContainerInspectRequest towerAccessToken(String towerAccessToken) {
        this.towerAccessToken = towerAccessToken;
        return this;
    }

    /**
     * Seqera Platform service endpoint from where container registry credentials are retrieved (optional). Default &#x60;https://api.cloud.seqera.io&#x60;.
     *
     * @return the towerEndpoint property value
     */
    public String getTowerEndpoint() {
        return towerEndpoint;
    }

    /**
     * Set the towerEndpoint property value
     *
     * @param towerEndpoint property value to set
     */
    public void setTowerEndpoint(String towerEndpoint) {
        this.towerEndpoint = towerEndpoint;
    }

    /**
     * Set towerEndpoint in a chainable fashion.
     *
     * @return The same instance of ContainerInspectRequest for chaining.
     */
    public ContainerInspectRequest towerEndpoint(String towerEndpoint) {
        this.towerEndpoint = towerEndpoint;
        return this;
    }

    /**
     * ID of the Seqera Platform workspace from where the container registry credentials are retrieved (optional). When omitted the personal workspace is used.
     *
     * @return the towerWorkspaceId property value
     */
    public Long getTowerWorkspaceId() {
        return towerWorkspaceId;
    }

    /**
     * Set the towerWorkspaceId property value
     *
     * @param towerWorkspaceId property value to set
     */
    public void setTowerWorkspaceId(Long towerWorkspaceId) {
        this.towerWorkspaceId = towerWorkspaceId;
    }

    /**
     * Set towerWorkspaceId in a chainable fashion.
     *
     * @return The same instance of ContainerInspectRequest for chaining.
     */
    public ContainerInspectRequest towerWorkspaceId(Long towerWorkspaceId) {
        this.towerWorkspaceId = towerWorkspaceId;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var containerInspectRequest = (ContainerInspectRequest) o;
        return Objects.equals(containerImage, containerInspectRequest.containerImage)
            && Objects.equals(towerAccessToken, containerInspectRequest.towerAccessToken)
            && Objects.equals(towerEndpoint, containerInspectRequest.towerEndpoint)
            && Objects.equals(towerWorkspaceId, containerInspectRequest.towerWorkspaceId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(containerImage, towerAccessToken, towerEndpoint, towerWorkspaceId);
    }

    @Override
    public String toString() {
        return "ContainerInspectRequest("
            + "containerImage: " + getContainerImage() + ", "
            + "towerAccessToken: " + getTowerAccessToken() + ", "
            + "towerEndpoint: " + getTowerEndpoint() + ", "
            + "towerWorkspaceId: " + getTowerWorkspaceId()
            + ")";
    }

}