/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.wave.api.v1.model.ContainerInspectConfigConfig;
import io.seqera.wave.api.v1.model.RootFS;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Configuration details of a container.
 */
@Serdeable
@JsonPropertyOrder({
    ContainerInspectConfig.JSON_PROPERTY_ARCHITECTURE,
    ContainerInspectConfig.JSON_PROPERTY_CONFIG,
    ContainerInspectConfig.JSON_PROPERTY_CONTAINER,
    ContainerInspectConfig.JSON_PROPERTY_CREATED,
    ContainerInspectConfig.JSON_PROPERTY_ROOTFS,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ContainerInspectConfig {

    public static final String JSON_PROPERTY_ARCHITECTURE = "architecture";
    public static final String JSON_PROPERTY_CONFIG = "config";
    public static final String JSON_PROPERTY_CONTAINER = "container";
    public static final String JSON_PROPERTY_CREATED = "created";
    public static final String JSON_PROPERTY_ROOTFS = "rootfs";

    @NotNull
    @JsonProperty(JSON_PROPERTY_ARCHITECTURE)
    private String architecture;

    @NotNull
    @Valid
    @JsonProperty(JSON_PROPERTY_CONFIG)
    private ContainerInspectConfigConfig config;

    @NotNull
    @JsonProperty(JSON_PROPERTY_CONTAINER)
    private String container;

    @NotNull
    @JsonProperty(JSON_PROPERTY_CREATED)
    private String created;

    @NotNull
    @Valid
    @JsonProperty(JSON_PROPERTY_ROOTFS)
    private RootFS rootfs;

    /**
     * @return the architecture property value
     */
    public String getArchitecture() {
        return architecture;
    }

    /**
     * Set the architecture property value
     *
     * @param architecture property value to set
     */
    public void setArchitecture(String architecture) {
        this.architecture = architecture;
    }

    /**
     * Set architecture in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfig for chaining.
     */
    public ContainerInspectConfig architecture(String architecture) {
        this.architecture = architecture;
        return this;
    }

    /**
     * @return the config property value
     */
    public ContainerInspectConfigConfig getConfig() {
        return config;
    }

    /**
     * Set the config property value
     *
     * @param config property value to set
     */
    public void setConfig(ContainerInspectConfigConfig config) {
        this.config = config;
    }

    /**
     * Set config in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfig for chaining.
     */
    public ContainerInspectConfig config(ContainerInspectConfigConfig config) {
        this.config = config;
        return this;
    }

    /**
     * @return the container property value
     */
    public String getContainer() {
        return container;
    }

    /**
     * Set the container property value
     *
     * @param container property value to set
     */
    public void setContainer(String container) {
        this.container = container;
    }

    /**
     * Set container in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfig for chaining.
     */
    public ContainerInspectConfig container(String container) {
        this.container = container;
        return this;
    }

    /**
     * @return the created property value
     */
    public String getCreated() {
        return created;
    }

    /**
     * Set the created property value
     *
     * @param created property value to set
     */
    public void setCreated(String created) {
        this.created = created;
    }

    /**
     * Set created in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfig for chaining.
     */
    public ContainerInspectConfig created(String created) {
        this.created = created;
        return this;
    }

    /**
     * @return the rootfs property value
     */
    public RootFS getRootfs() {
        return rootfs;
    }

    /**
     * Set the rootfs property value
     *
     * @param rootfs property value to set
     */
    public void setRootfs(RootFS rootfs) {
        this.rootfs = rootfs;
    }

    /**
     * Set rootfs in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfig for chaining.
     */
    public ContainerInspectConfig rootfs(RootFS rootfs) {
        this.rootfs = rootfs;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var containerInspectConfig = (ContainerInspectConfig) o;
        return Objects.equals(architecture, containerInspectConfig.architecture)
            && Objects.equals(config, containerInspectConfig.config)
            && Objects.equals(container, containerInspectConfig.container)
            && Objects.equals(created, containerInspectConfig.created)
            && Objects.equals(rootfs, containerInspectConfig.rootfs);
    }

    @Override
    public int hashCode() {
        return Objects.hash(architecture, config, container, created, rootfs);
    }

    @Override
    public String toString() {
        return "ContainerInspectConfig("
            + "architecture: " + getArchitecture() + ", "
            + "config: " + getConfig() + ", "
            + "container: " + getContainer() + ", "
            + "created: " + getCreated() + ", "
            + "rootfs: " + getRootfs()
            + ")";
    }

}