/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.wave.api.v1.model.ContainerInspectResponseContainer;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Response payload for inspecting a container.
 */
@Serdeable
@JsonPropertyOrder(ContainerInspectResponse.JSON_PROPERTY_CONTAINER)
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ContainerInspectResponse {

    public static final String JSON_PROPERTY_CONTAINER = "Container";

    @NotNull
    @Valid
    @JsonProperty(JSON_PROPERTY_CONTAINER)
    private ContainerInspectResponseContainer container;

    /**
     * @return the container property value
     */
    public ContainerInspectResponseContainer getContainer() {
        return container;
    }

    /**
     * Set the container property value
     *
     * @param container property value to set
     */
    public void setContainer(ContainerInspectResponseContainer container) {
        this.container = container;
    }

    /**
     * Set container in a chainable fashion.
     *
     * @return The same instance of ContainerInspectResponse for chaining.
     */
    public ContainerInspectResponse container(ContainerInspectResponseContainer container) {
        this.container = container;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var containerInspectResponse = (ContainerInspectResponse) o;
        return Objects.equals(container, containerInspectResponse.container);
    }

    @Override
    public int hashCode() {
        return Objects.hash(container);
    }

    @Override
    public String toString() {
        return "ContainerInspectResponse("
            + "container: " + getContainer()
            + ")";
    }

}