/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.wave.api.v1.model.ContainerPlatform;
import io.seqera.wave.api.v1.model.Status;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Response payload for container mirroring.
 */
@Serdeable
@JsonPropertyOrder({
    ContainerMirrorResponse.JSON_PROPERTY_MIRROR_ID,
    ContainerMirrorResponse.JSON_PROPERTY_DIGEST,
    ContainerMirrorResponse.JSON_PROPERTY_SOURCE_IMAGE,
    ContainerMirrorResponse.JSON_PROPERTY_TARGET_IMAGE,
    ContainerMirrorResponse.JSON_PROPERTY_PLATFORM,
    ContainerMirrorResponse.JSON_PROPERTY_CREATION_TIME,
    ContainerMirrorResponse.JSON_PROPERTY_STATUS,
    ContainerMirrorResponse.JSON_PROPERTY_DURATION,
    ContainerMirrorResponse.JSON_PROPERTY_EXIT_CODE,
    ContainerMirrorResponse.JSON_PROPERTY_LOGS,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ContainerMirrorResponse {

    public static final String JSON_PROPERTY_MIRROR_ID = "mirrorId";
    public static final String JSON_PROPERTY_DIGEST = "digest";
    public static final String JSON_PROPERTY_SOURCE_IMAGE = "sourceImage";
    public static final String JSON_PROPERTY_TARGET_IMAGE = "targetImage";
    public static final String JSON_PROPERTY_PLATFORM = "platform";
    public static final String JSON_PROPERTY_CREATION_TIME = "creationTime";
    public static final String JSON_PROPERTY_STATUS = "status";
    public static final String JSON_PROPERTY_DURATION = "duration";
    public static final String JSON_PROPERTY_EXIT_CODE = "exitCode";
    public static final String JSON_PROPERTY_LOGS = "logs";

    @NotNull
    @JsonProperty(JSON_PROPERTY_MIRROR_ID)
    private String mirrorId;

    @NotNull
    @JsonProperty(JSON_PROPERTY_DIGEST)
    private String digest;

    @NotNull
    @JsonProperty(JSON_PROPERTY_SOURCE_IMAGE)
    private String sourceImage;

    @NotNull
    @JsonProperty(JSON_PROPERTY_TARGET_IMAGE)
    private String targetImage;

    @NotNull
    @Valid
    @JsonProperty(JSON_PROPERTY_PLATFORM)
    private ContainerPlatform platform;

    @NotNull
    @JsonProperty(JSON_PROPERTY_CREATION_TIME)
    private String creationTime;

    @NotNull
    @JsonProperty(JSON_PROPERTY_STATUS)
    private Status status;

    @NotNull
    @JsonProperty(JSON_PROPERTY_DURATION)
    private String duration;

    @NotNull
    @JsonProperty(JSON_PROPERTY_EXIT_CODE)
    private Integer exitCode;

    @NotNull
    @JsonProperty(JSON_PROPERTY_LOGS)
    private String logs;

    /**
     * @return the mirrorId property value
     */
    public String getMirrorId() {
        return mirrorId;
    }

    /**
     * Set the mirrorId property value
     *
     * @param mirrorId property value to set
     */
    public void setMirrorId(String mirrorId) {
        this.mirrorId = mirrorId;
    }

    /**
     * Set mirrorId in a chainable fashion.
     *
     * @return The same instance of ContainerMirrorResponse for chaining.
     */
    public ContainerMirrorResponse mirrorId(String mirrorId) {
        this.mirrorId = mirrorId;
        return this;
    }

    /**
     * @return the digest property value
     */
    public String getDigest() {
        return digest;
    }

    /**
     * Set the digest property value
     *
     * @param digest property value to set
     */
    public void setDigest(String digest) {
        this.digest = digest;
    }

    /**
     * Set digest in a chainable fashion.
     *
     * @return The same instance of ContainerMirrorResponse for chaining.
     */
    public ContainerMirrorResponse digest(String digest) {
        this.digest = digest;
        return this;
    }

    /**
     * @return the sourceImage property value
     */
    public String getSourceImage() {
        return sourceImage;
    }

    /**
     * Set the sourceImage property value
     *
     * @param sourceImage property value to set
     */
    public void setSourceImage(String sourceImage) {
        this.sourceImage = sourceImage;
    }

    /**
     * Set sourceImage in a chainable fashion.
     *
     * @return The same instance of ContainerMirrorResponse for chaining.
     */
    public ContainerMirrorResponse sourceImage(String sourceImage) {
        this.sourceImage = sourceImage;
        return this;
    }

    /**
     * @return the targetImage property value
     */
    public String getTargetImage() {
        return targetImage;
    }

    /**
     * Set the targetImage property value
     *
     * @param targetImage property value to set
     */
    public void setTargetImage(String targetImage) {
        this.targetImage = targetImage;
    }

    /**
     * Set targetImage in a chainable fashion.
     *
     * @return The same instance of ContainerMirrorResponse for chaining.
     */
    public ContainerMirrorResponse targetImage(String targetImage) {
        this.targetImage = targetImage;
        return this;
    }

    /**
     * @return the platform property value
     */
    public ContainerPlatform getPlatform() {
        return platform;
    }

    /**
     * Set the platform property value
     *
     * @param platform property value to set
     */
    public void setPlatform(ContainerPlatform platform) {
        this.platform = platform;
    }

    /**
     * Set platform in a chainable fashion.
     *
     * @return The same instance of ContainerMirrorResponse for chaining.
     */
    public ContainerMirrorResponse platform(ContainerPlatform platform) {
        this.platform = platform;
        return this;
    }

    /**
     * @return the creationTime property value
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Set the creationTime property value
     *
     * @param creationTime property value to set
     */
    public void setCreationTime(String creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Set creationTime in a chainable fashion.
     *
     * @return The same instance of ContainerMirrorResponse for chaining.
     */
    public ContainerMirrorResponse creationTime(String creationTime) {
        this.creationTime = creationTime;
        return this;
    }

    /**
     * @return the status property value
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Set the status property value
     *
     * @param status property value to set
     */
    public void setStatus(Status status) {
        this.status = status;
    }

    /**
     * Set status in a chainable fashion.
     *
     * @return The same instance of ContainerMirrorResponse for chaining.
     */
    public ContainerMirrorResponse status(Status status) {
        this.status = status;
        return this;
    }

    /**
     * @return the duration property value
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Set the duration property value
     *
     * @param duration property value to set
     */
    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * Set duration in a chainable fashion.
     *
     * @return The same instance of ContainerMirrorResponse for chaining.
     */
    public ContainerMirrorResponse duration(String duration) {
        this.duration = duration;
        return this;
    }

    /**
     * @return the exitCode property value
     */
    public Integer getExitCode() {
        return exitCode;
    }

    /**
     * Set the exitCode property value
     *
     * @param exitCode property value to set
     */
    public void setExitCode(Integer exitCode) {
        this.exitCode = exitCode;
    }

    /**
     * Set exitCode in a chainable fashion.
     *
     * @return The same instance of ContainerMirrorResponse for chaining.
     */
    public ContainerMirrorResponse exitCode(Integer exitCode) {
        this.exitCode = exitCode;
        return this;
    }

    /**
     * @return the logs property value
     */
    public String getLogs() {
        return logs;
    }

    /**
     * Set the logs property value
     *
     * @param logs property value to set
     */
    public void setLogs(String logs) {
        this.logs = logs;
    }

    /**
     * Set logs in a chainable fashion.
     *
     * @return The same instance of ContainerMirrorResponse for chaining.
     */
    public ContainerMirrorResponse logs(String logs) {
        this.logs = logs;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var containerMirrorResponse = (ContainerMirrorResponse) o;
        return Objects.equals(mirrorId, containerMirrorResponse.mirrorId)
            && Objects.equals(digest, containerMirrorResponse.digest)
            && Objects.equals(sourceImage, containerMirrorResponse.sourceImage)
            && Objects.equals(targetImage, containerMirrorResponse.targetImage)
            && Objects.equals(platform, containerMirrorResponse.platform)
            && Objects.equals(creationTime, containerMirrorResponse.creationTime)
            && Objects.equals(status, containerMirrorResponse.status)
            && Objects.equals(duration, containerMirrorResponse.duration)
            && Objects.equals(exitCode, containerMirrorResponse.exitCode)
            && Objects.equals(logs, containerMirrorResponse.logs);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mirrorId, digest, sourceImage, targetImage, platform, creationTime, status, duration, exitCode, logs);
    }

    @Override
    public String toString() {
        return "ContainerMirrorResponse("
            + "mirrorId: " + getMirrorId() + ", "
            + "digest: " + getDigest() + ", "
            + "sourceImage: " + getSourceImage() + ", "
            + "targetImage: " + getTargetImage() + ", "
            + "platform: " + getPlatform() + ", "
            + "creationTime: " + getCreationTime() + ", "
            + "status: " + getStatus() + ", "
            + "duration: " + getDuration() + ", "
            + "exitCode: " + getExitCode() + ", "
            + "logs: " + getLogs()
            + ")";
    }

}