/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.wave.api.v1.model.ContainerStatus;
import io.seqera.wave.api.v1.model.Vulnerability;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Response payload for container status.
 */
@Serdeable
@JsonPropertyOrder({
    ContainerStatusResponse.JSON_PROPERTY_ID,
    ContainerStatusResponse.JSON_PROPERTY_STATUS,
    ContainerStatusResponse.JSON_PROPERTY_BUILD_ID,
    ContainerStatusResponse.JSON_PROPERTY_SCAN_ID,
    ContainerStatusResponse.JSON_PROPERTY_SUCCEEDED,
    ContainerStatusResponse.JSON_PROPERTY_DETAILS_URI,
    ContainerStatusResponse.JSON_PROPERTY_CREATION_TIME,
    ContainerStatusResponse.JSON_PROPERTY_DURATION,
    ContainerStatusResponse.JSON_PROPERTY_MIRROR_ID,
    ContainerStatusResponse.JSON_PROPERTY_VULNERABILITIES,
    ContainerStatusResponse.JSON_PROPERTY_REASON,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ContainerStatusResponse {

    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_STATUS = "status";
    public static final String JSON_PROPERTY_BUILD_ID = "buildId";
    public static final String JSON_PROPERTY_SCAN_ID = "scanId";
    public static final String JSON_PROPERTY_SUCCEEDED = "succeeded";
    public static final String JSON_PROPERTY_DETAILS_URI = "detailsUri";
    public static final String JSON_PROPERTY_CREATION_TIME = "creationTime";
    public static final String JSON_PROPERTY_DURATION = "duration";
    public static final String JSON_PROPERTY_MIRROR_ID = "mirrorId";
    public static final String JSON_PROPERTY_VULNERABILITIES = "vulnerabilities";
    public static final String JSON_PROPERTY_REASON = "reason";

    @NotNull
    @JsonProperty(JSON_PROPERTY_ID)
    private String id;

    @NotNull
    @JsonProperty(JSON_PROPERTY_STATUS)
    private ContainerStatus status;

    @NotNull
    @JsonProperty(JSON_PROPERTY_BUILD_ID)
    private String buildId;

    @NotNull
    @JsonProperty(JSON_PROPERTY_SCAN_ID)
    private String scanId;

    @NotNull
    @JsonProperty(JSON_PROPERTY_SUCCEEDED)
    private Boolean succeeded;

    @NotNull
    @JsonProperty(JSON_PROPERTY_DETAILS_URI)
    private String detailsUri;

    @NotNull
    @JsonProperty(JSON_PROPERTY_CREATION_TIME)
    private String creationTime;

    @NotNull
    @JsonProperty(JSON_PROPERTY_DURATION)
    private String duration;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_MIRROR_ID)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String mirrorId;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_VULNERABILITIES)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Map<String, @Valid Vulnerability> vulnerabilities;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_REASON)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String reason;

    /**
     * @return the id property value
     */
    public String getId() {
        return id;
    }

    /**
     * Set the id property value
     *
     * @param id property value to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Set id in a chainable fashion.
     *
     * @return The same instance of ContainerStatusResponse for chaining.
     */
    public ContainerStatusResponse id(String id) {
        this.id = id;
        return this;
    }

    /**
     * @return the status property value
     */
    public ContainerStatus getStatus() {
        return status;
    }

    /**
     * Set the status property value
     *
     * @param status property value to set
     */
    public void setStatus(ContainerStatus status) {
        this.status = status;
    }

    /**
     * Set status in a chainable fashion.
     *
     * @return The same instance of ContainerStatusResponse for chaining.
     */
    public ContainerStatusResponse status(ContainerStatus status) {
        this.status = status;
        return this;
    }

    /**
     * @return the buildId property value
     */
    public String getBuildId() {
        return buildId;
    }

    /**
     * Set the buildId property value
     *
     * @param buildId property value to set
     */
    public void setBuildId(String buildId) {
        this.buildId = buildId;
    }

    /**
     * Set buildId in a chainable fashion.
     *
     * @return The same instance of ContainerStatusResponse for chaining.
     */
    public ContainerStatusResponse buildId(String buildId) {
        this.buildId = buildId;
        return this;
    }

    /**
     * @return the scanId property value
     */
    public String getScanId() {
        return scanId;
    }

    /**
     * Set the scanId property value
     *
     * @param scanId property value to set
     */
    public void setScanId(String scanId) {
        this.scanId = scanId;
    }

    /**
     * Set scanId in a chainable fashion.
     *
     * @return The same instance of ContainerStatusResponse for chaining.
     */
    public ContainerStatusResponse scanId(String scanId) {
        this.scanId = scanId;
        return this;
    }

    /**
     * @return the succeeded property value
     */
    public Boolean getSucceeded() {
        return succeeded;
    }

    /**
     * Set the succeeded property value
     *
     * @param succeeded property value to set
     */
    public void setSucceeded(Boolean succeeded) {
        this.succeeded = succeeded;
    }

    /**
     * Set succeeded in a chainable fashion.
     *
     * @return The same instance of ContainerStatusResponse for chaining.
     */
    public ContainerStatusResponse succeeded(Boolean succeeded) {
        this.succeeded = succeeded;
        return this;
    }

    /**
     * @return the detailsUri property value
     */
    public String getDetailsUri() {
        return detailsUri;
    }

    /**
     * Set the detailsUri property value
     *
     * @param detailsUri property value to set
     */
    public void setDetailsUri(String detailsUri) {
        this.detailsUri = detailsUri;
    }

    /**
     * Set detailsUri in a chainable fashion.
     *
     * @return The same instance of ContainerStatusResponse for chaining.
     */
    public ContainerStatusResponse detailsUri(String detailsUri) {
        this.detailsUri = detailsUri;
        return this;
    }

    /**
     * @return the creationTime property value
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Set the creationTime property value
     *
     * @param creationTime property value to set
     */
    public void setCreationTime(String creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * Set creationTime in a chainable fashion.
     *
     * @return The same instance of ContainerStatusResponse for chaining.
     */
    public ContainerStatusResponse creationTime(String creationTime) {
        this.creationTime = creationTime;
        return this;
    }

    /**
     * @return the duration property value
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Set the duration property value
     *
     * @param duration property value to set
     */
    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * Set duration in a chainable fashion.
     *
     * @return The same instance of ContainerStatusResponse for chaining.
     */
    public ContainerStatusResponse duration(String duration) {
        this.duration = duration;
        return this;
    }

    /**
     * @return the mirrorId property value
     */
    public String getMirrorId() {
        return mirrorId;
    }

    /**
     * Set the mirrorId property value
     *
     * @param mirrorId property value to set
     */
    public void setMirrorId(String mirrorId) {
        this.mirrorId = mirrorId;
    }

    /**
     * Set mirrorId in a chainable fashion.
     *
     * @return The same instance of ContainerStatusResponse for chaining.
     */
    public ContainerStatusResponse mirrorId(String mirrorId) {
        this.mirrorId = mirrorId;
        return this;
    }

    /**
     * @return the vulnerabilities property value
     */
    public Map<String, @Valid Vulnerability> getVulnerabilities() {
        return vulnerabilities;
    }

    /**
     * Set the vulnerabilities property value
     *
     * @param vulnerabilities property value to set
     */
    public void setVulnerabilities(Map<String, @Valid Vulnerability> vulnerabilities) {
        this.vulnerabilities = vulnerabilities;
    }

    /**
     * Set vulnerabilities in a chainable fashion.
     *
     * @return The same instance of ContainerStatusResponse for chaining.
     */
    public ContainerStatusResponse vulnerabilities(Map<String, @Valid Vulnerability> vulnerabilities) {
        this.vulnerabilities = vulnerabilities;
        return this;
    }

    /**
     * Set the value for the key for the vulnerabilities map property in a chainable fashion.
     *
     * @return The same instance of ContainerStatusResponse for chaining.
     */
    public ContainerStatusResponse putVulnerabilitiesItem(String key, Vulnerability vulnerabilitiesItem) {
        if (vulnerabilities == null) {
            vulnerabilities = new HashMap<>();
        }
        vulnerabilities.put(key, vulnerabilitiesItem);
        return this;
    }

    /**
     * @return the reason property value
     */
    public String getReason() {
        return reason;
    }

    /**
     * Set the reason property value
     *
     * @param reason property value to set
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * Set reason in a chainable fashion.
     *
     * @return The same instance of ContainerStatusResponse for chaining.
     */
    public ContainerStatusResponse reason(String reason) {
        this.reason = reason;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var containerStatusResponse = (ContainerStatusResponse) o;
        return Objects.equals(id, containerStatusResponse.id)
            && Objects.equals(status, containerStatusResponse.status)
            && Objects.equals(buildId, containerStatusResponse.buildId)
            && Objects.equals(scanId, containerStatusResponse.scanId)
            && Objects.equals(succeeded, containerStatusResponse.succeeded)
            && Objects.equals(detailsUri, containerStatusResponse.detailsUri)
            && Objects.equals(creationTime, containerStatusResponse.creationTime)
            && Objects.equals(duration, containerStatusResponse.duration)
            && Objects.equals(mirrorId, containerStatusResponse.mirrorId)
            && Objects.equals(vulnerabilities, containerStatusResponse.vulnerabilities)
            && Objects.equals(reason, containerStatusResponse.reason);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, status, buildId, scanId, succeeded, detailsUri, creationTime, duration, mirrorId, vulnerabilities, reason);
    }

    @Override
    public String toString() {
        return "ContainerStatusResponse("
            + "id: " + getId() + ", "
            + "status: " + getStatus() + ", "
            + "buildId: " + getBuildId() + ", "
            + "scanId: " + getScanId() + ", "
            + "succeeded: " + getSucceeded() + ", "
            + "detailsUri: " + getDetailsUri() + ", "
            + "creationTime: " + getCreationTime() + ", "
            + "duration: " + getDuration() + ", "
            + "mirrorId: " + getMirrorId() + ", "
            + "vulnerabilities: " + getVulnerabilities() + ", "
            + "reason: " + getReason()
            + ")";
    }

}