/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.wave.api.v1.model.ContainerLayer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Configuration details for a container.
 */
@Serdeable
@JsonPropertyOrder({
    ContainerConfig.JSON_PROPERTY_CMD,
    ContainerConfig.JSON_PROPERTY_ENTRYPOINT,
    ContainerConfig.JSON_PROPERTY_ENV,
    ContainerConfig.JSON_PROPERTY_LAYERS,
    ContainerConfig.JSON_PROPERTY_WORKING_DIR,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ContainerConfig {

    public static final String JSON_PROPERTY_CMD = "cmd";
    public static final String JSON_PROPERTY_ENTRYPOINT = "entrypoint";
    public static final String JSON_PROPERTY_ENV = "env";
    public static final String JSON_PROPERTY_LAYERS = "layers";
    public static final String JSON_PROPERTY_WORKING_DIR = "workingDir";

    /**
     * The launch command to be used by the Wave container, e.g., &#x60;[&#39;echo&#39;, &#39;Hello world&#39;]&#x60; (optional).
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_CMD)
    private List<@NotNull String> cmd = new ArrayList<>();

    /**
     * The container entrypoint command, e.g., &#x60;[&#39;/bin/bash&#39;]&#x60;.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_ENTRYPOINT)
    private List<@NotNull String> entrypoint = new ArrayList<>();

    /**
     * The environment variables to be defined in the Wave container, e.g., &#x60;[&#39;FOO&#x3D;one&#39;,&#39;BAR&#x3D;two&#39;]&#x60; (optional).
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_ENV)
    private List<@NotNull String> env = new ArrayList<>();

    @NotNull
    @JsonProperty(JSON_PROPERTY_LAYERS)
    private List<@Valid ContainerLayer> layers = new ArrayList<>();

    /**
     * The work directory to be used in the Wave container, e.g., &#x60;/some/work/dir&#x60; (optional).
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_WORKING_DIR)
    private String workingDir;

    /**
     * The launch command to be used by the Wave container, e.g., &#x60;[&#39;echo&#39;, &#39;Hello world&#39;]&#x60; (optional).
     *
     * @return the cmd property value
     */
    public List<@NotNull String> getCmd() {
        return cmd;
    }

    /**
     * Set the cmd property value
     *
     * @param cmd property value to set
     */
    public void setCmd(List<@NotNull String> cmd) {
        this.cmd = cmd;
    }

    /**
     * Set cmd in a chainable fashion.
     *
     * @return The same instance of ContainerConfig for chaining.
     */
    public ContainerConfig cmd(List<@NotNull String> cmd) {
        this.cmd = cmd;
        return this;
    }
    /**
     * Add an item to the cmd property in a chainable fashion.
     *
     * @return The same instance of ContainerConfig for chaining.
     */
    public ContainerConfig addCmdItem(String cmdItem) {
        cmd.add(cmdItem);
        return this;
    }

    /**
     * The container entrypoint command, e.g., &#x60;[&#39;/bin/bash&#39;]&#x60;.
     *
     * @return the entrypoint property value
     */
    public List<@NotNull String> getEntrypoint() {
        return entrypoint;
    }

    /**
     * Set the entrypoint property value
     *
     * @param entrypoint property value to set
     */
    public void setEntrypoint(List<@NotNull String> entrypoint) {
        this.entrypoint = entrypoint;
    }

    /**
     * Set entrypoint in a chainable fashion.
     *
     * @return The same instance of ContainerConfig for chaining.
     */
    public ContainerConfig entrypoint(List<@NotNull String> entrypoint) {
        this.entrypoint = entrypoint;
        return this;
    }
    /**
     * Add an item to the entrypoint property in a chainable fashion.
     *
     * @return The same instance of ContainerConfig for chaining.
     */
    public ContainerConfig addEntrypointItem(String entrypointItem) {
        entrypoint.add(entrypointItem);
        return this;
    }

    /**
     * The environment variables to be defined in the Wave container, e.g., &#x60;[&#39;FOO&#x3D;one&#39;,&#39;BAR&#x3D;two&#39;]&#x60; (optional).
     *
     * @return the env property value
     */
    public List<@NotNull String> getEnv() {
        return env;
    }

    /**
     * Set the env property value
     *
     * @param env property value to set
     */
    public void setEnv(List<@NotNull String> env) {
        this.env = env;
    }

    /**
     * Set env in a chainable fashion.
     *
     * @return The same instance of ContainerConfig for chaining.
     */
    public ContainerConfig env(List<@NotNull String> env) {
        this.env = env;
        return this;
    }
    /**
     * Add an item to the env property in a chainable fashion.
     *
     * @return The same instance of ContainerConfig for chaining.
     */
    public ContainerConfig addEnvItem(String envItem) {
        env.add(envItem);
        return this;
    }

    /**
     * @return the layers property value
     */
    public List<@Valid ContainerLayer> getLayers() {
        return layers;
    }

    /**
     * Set the layers property value
     *
     * @param layers property value to set
     */
    public void setLayers(List<@Valid ContainerLayer> layers) {
        this.layers = layers;
    }

    /**
     * Set layers in a chainable fashion.
     *
     * @return The same instance of ContainerConfig for chaining.
     */
    public ContainerConfig layers(List<@Valid ContainerLayer> layers) {
        this.layers = layers;
        return this;
    }
    /**
     * Add an item to the layers property in a chainable fashion.
     *
     * @return The same instance of ContainerConfig for chaining.
     */
    public ContainerConfig addLayersItem(ContainerLayer layersItem) {
        layers.add(layersItem);
        return this;
    }

    /**
     * The work directory to be used in the Wave container, e.g., &#x60;/some/work/dir&#x60; (optional).
     *
     * @return the workingDir property value
     */
    public String getWorkingDir() {
        return workingDir;
    }

    /**
     * Set the workingDir property value
     *
     * @param workingDir property value to set
     */
    public void setWorkingDir(String workingDir) {
        this.workingDir = workingDir;
    }

    /**
     * Set workingDir in a chainable fashion.
     *
     * @return The same instance of ContainerConfig for chaining.
     */
    public ContainerConfig workingDir(String workingDir) {
        this.workingDir = workingDir;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var containerConfig = (ContainerConfig) o;
        return Objects.equals(cmd, containerConfig.cmd)
            && Objects.equals(entrypoint, containerConfig.entrypoint)
            && Objects.equals(env, containerConfig.env)
            && Objects.equals(layers, containerConfig.layers)
            && Objects.equals(workingDir, containerConfig.workingDir);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cmd, entrypoint, env, layers, workingDir);
    }

    @Override
    public String toString() {
        return "ContainerConfig("
            + "cmd: " + getCmd() + ", "
            + "entrypoint: " + getEntrypoint() + ", "
            + "env: " + getEnv() + ", "
            + "layers: " + getLayers() + ", "
            + "workingDir: " + getWorkingDir()
            + ")";
    }

}