/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.wave.api.v1.model.ContainerInspectConfig;
import io.seqera.wave.api.v1.model.Manifest;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * ContainerInspectResponseContainer
 */
@Serdeable
@JsonPropertyOrder({
    ContainerInspectResponseContainer.JSON_PROPERTY_REGISTRY,
    ContainerInspectResponseContainer.JSON_PROPERTY_HOST_NAME,
    ContainerInspectResponseContainer.JSON_PROPERTY_IMAGE_NAME,
    ContainerInspectResponseContainer.JSON_PROPERTY_REFERENCE,
    ContainerInspectResponseContainer.JSON_PROPERTY_DIGEST,
    ContainerInspectResponseContainer.JSON_PROPERTY_CONFIG,
    ContainerInspectResponseContainer.JSON_PROPERTY_MANIFEST,
    ContainerInspectResponseContainer.JSON_PROPERTY_V1,
    ContainerInspectResponseContainer.JSON_PROPERTY_V2,
    ContainerInspectResponseContainer.JSON_PROPERTY_OCI,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ContainerInspectResponseContainer {

    public static final String JSON_PROPERTY_REGISTRY = "registry";
    public static final String JSON_PROPERTY_HOST_NAME = "hostName";
    public static final String JSON_PROPERTY_IMAGE_NAME = "imageName";
    public static final String JSON_PROPERTY_REFERENCE = "reference";
    public static final String JSON_PROPERTY_DIGEST = "digest";
    public static final String JSON_PROPERTY_CONFIG = "config";
    public static final String JSON_PROPERTY_MANIFEST = "manifest";
    public static final String JSON_PROPERTY_V1 = "v1";
    public static final String JSON_PROPERTY_V2 = "v2";
    public static final String JSON_PROPERTY_OCI = "oci";

    @NotNull
    @JsonProperty(JSON_PROPERTY_REGISTRY)
    private String registry;

    @NotNull
    @JsonProperty(JSON_PROPERTY_HOST_NAME)
    private String hostName;

    @NotNull
    @JsonProperty(JSON_PROPERTY_IMAGE_NAME)
    private String imageName;

    @NotNull
    @JsonProperty(JSON_PROPERTY_REFERENCE)
    private String reference;

    @NotNull
    @JsonProperty(JSON_PROPERTY_DIGEST)
    private String digest;

    @NotNull
    @Valid
    @JsonProperty(JSON_PROPERTY_CONFIG)
    private ContainerInspectConfig config;

    @NotNull
    @Valid
    @JsonProperty(JSON_PROPERTY_MANIFEST)
    private Manifest manifest;

    @NotNull
    @JsonProperty(JSON_PROPERTY_V1)
    private Boolean v1;

    @NotNull
    @JsonProperty(JSON_PROPERTY_V2)
    private Boolean v2;

    @NotNull
    @JsonProperty(JSON_PROPERTY_OCI)
    private Boolean oci;

    /**
     * @return the registry property value
     */
    public String getRegistry() {
        return registry;
    }

    /**
     * Set the registry property value
     *
     * @param registry property value to set
     */
    public void setRegistry(String registry) {
        this.registry = registry;
    }

    /**
     * Set registry in a chainable fashion.
     *
     * @return The same instance of ContainerInspectResponseContainer for chaining.
     */
    public ContainerInspectResponseContainer registry(String registry) {
        this.registry = registry;
        return this;
    }

    /**
     * @return the hostName property value
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * Set the hostName property value
     *
     * @param hostName property value to set
     */
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }

    /**
     * Set hostName in a chainable fashion.
     *
     * @return The same instance of ContainerInspectResponseContainer for chaining.
     */
    public ContainerInspectResponseContainer hostName(String hostName) {
        this.hostName = hostName;
        return this;
    }

    /**
     * @return the imageName property value
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * Set the imageName property value
     *
     * @param imageName property value to set
     */
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    /**
     * Set imageName in a chainable fashion.
     *
     * @return The same instance of ContainerInspectResponseContainer for chaining.
     */
    public ContainerInspectResponseContainer imageName(String imageName) {
        this.imageName = imageName;
        return this;
    }

    /**
     * @return the reference property value
     */
    public String getReference() {
        return reference;
    }

    /**
     * Set the reference property value
     *
     * @param reference property value to set
     */
    public void setReference(String reference) {
        this.reference = reference;
    }

    /**
     * Set reference in a chainable fashion.
     *
     * @return The same instance of ContainerInspectResponseContainer for chaining.
     */
    public ContainerInspectResponseContainer reference(String reference) {
        this.reference = reference;
        return this;
    }

    /**
     * @return the digest property value
     */
    public String getDigest() {
        return digest;
    }

    /**
     * Set the digest property value
     *
     * @param digest property value to set
     */
    public void setDigest(String digest) {
        this.digest = digest;
    }

    /**
     * Set digest in a chainable fashion.
     *
     * @return The same instance of ContainerInspectResponseContainer for chaining.
     */
    public ContainerInspectResponseContainer digest(String digest) {
        this.digest = digest;
        return this;
    }

    /**
     * @return the config property value
     */
    public ContainerInspectConfig getConfig() {
        return config;
    }

    /**
     * Set the config property value
     *
     * @param config property value to set
     */
    public void setConfig(ContainerInspectConfig config) {
        this.config = config;
    }

    /**
     * Set config in a chainable fashion.
     *
     * @return The same instance of ContainerInspectResponseContainer for chaining.
     */
    public ContainerInspectResponseContainer config(ContainerInspectConfig config) {
        this.config = config;
        return this;
    }

    /**
     * @return the manifest property value
     */
    public Manifest getManifest() {
        return manifest;
    }

    /**
     * Set the manifest property value
     *
     * @param manifest property value to set
     */
    public void setManifest(Manifest manifest) {
        this.manifest = manifest;
    }

    /**
     * Set manifest in a chainable fashion.
     *
     * @return The same instance of ContainerInspectResponseContainer for chaining.
     */
    public ContainerInspectResponseContainer manifest(Manifest manifest) {
        this.manifest = manifest;
        return this;
    }

    /**
     * @return the v1 property value
     */
    public Boolean getV1() {
        return v1;
    }

    /**
     * Set the v1 property value
     *
     * @param v1 property value to set
     */
    public void setV1(Boolean v1) {
        this.v1 = v1;
    }

    /**
     * Set v1 in a chainable fashion.
     *
     * @return The same instance of ContainerInspectResponseContainer for chaining.
     */
    public ContainerInspectResponseContainer v1(Boolean v1) {
        this.v1 = v1;
        return this;
    }

    /**
     * @return the v2 property value
     */
    public Boolean getV2() {
        return v2;
    }

    /**
     * Set the v2 property value
     *
     * @param v2 property value to set
     */
    public void setV2(Boolean v2) {
        this.v2 = v2;
    }

    /**
     * Set v2 in a chainable fashion.
     *
     * @return The same instance of ContainerInspectResponseContainer for chaining.
     */
    public ContainerInspectResponseContainer v2(Boolean v2) {
        this.v2 = v2;
        return this;
    }

    /**
     * @return the oci property value
     */
    public Boolean getOci() {
        return oci;
    }

    /**
     * Set the oci property value
     *
     * @param oci property value to set
     */
    public void setOci(Boolean oci) {
        this.oci = oci;
    }

    /**
     * Set oci in a chainable fashion.
     *
     * @return The same instance of ContainerInspectResponseContainer for chaining.
     */
    public ContainerInspectResponseContainer oci(Boolean oci) {
        this.oci = oci;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var containerInspectResponseContainer = (ContainerInspectResponseContainer) o;
        return Objects.equals(registry, containerInspectResponseContainer.registry)
            && Objects.equals(hostName, containerInspectResponseContainer.hostName)
            && Objects.equals(imageName, containerInspectResponseContainer.imageName)
            && Objects.equals(reference, containerInspectResponseContainer.reference)
            && Objects.equals(digest, containerInspectResponseContainer.digest)
            && Objects.equals(config, containerInspectResponseContainer.config)
            && Objects.equals(manifest, containerInspectResponseContainer.manifest)
            && Objects.equals(v1, containerInspectResponseContainer.v1)
            && Objects.equals(v2, containerInspectResponseContainer.v2)
            && Objects.equals(oci, containerInspectResponseContainer.oci);
    }

    @Override
    public int hashCode() {
        return Objects.hash(registry, hostName, imageName, reference, digest, config, manifest, v1, v2, oci);
    }

    @Override
    public String toString() {
        return "ContainerInspectResponseContainer("
            + "registry: " + getRegistry() + ", "
            + "hostName: " + getHostName() + ", "
            + "imageName: " + getImageName() + ", "
            + "reference: " + getReference() + ", "
            + "digest: " + getDigest() + ", "
            + "config: " + getConfig() + ", "
            + "manifest: " + getManifest() + ", "
            + "v1: " + getV1() + ", "
            + "v2: " + getV2() + ", "
            + "oci: " + getOci()
            + ")";
    }

}