/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.wave.api.v1.model.ContainerConfig;
import io.seqera.wave.api.v1.model.ContainerLayer;
import io.seqera.wave.api.v1.model.ContainerRequestFormat;
import io.seqera.wave.api.v1.model.ContainerRequestNameStrategy;
import io.seqera.wave.api.v1.model.PackagesSpec;
import io.seqera.wave.api.v1.model.ScanLevel;
import io.seqera.wave.api.v1.model.ScanMode;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Request payload for creating a container token.
 */
@Serdeable
@JsonPropertyOrder({
    ContainerRequest.JSON_PROPERTY_CONTAINER_PLATFORM,
    ContainerRequest.JSON_PROPERTY_FORMAT,
    ContainerRequest.JSON_PROPERTY_BUILD_CONTEXT,
    ContainerRequest.JSON_PROPERTY_BUILD_REPOSITORY,
    ContainerRequest.JSON_PROPERTY_CACHE_REPOSITORY,
    ContainerRequest.JSON_PROPERTY_CONTAINER_CONFIG,
    ContainerRequest.JSON_PROPERTY_CONTAINER_FILE,
    ContainerRequest.JSON_PROPERTY_CONTAINER_IMAGE,
    ContainerRequest.JSON_PROPERTY_CONTAINER_INCLUDES,
    ContainerRequest.JSON_PROPERTY_DRY_RUN,
    ContainerRequest.JSON_PROPERTY_FINGERPRINT,
    ContainerRequest.JSON_PROPERTY_FREEZE,
    ContainerRequest.JSON_PROPERTY_NAME_STRATEGY,
    ContainerRequest.JSON_PROPERTY_MIRROR,
    ContainerRequest.JSON_PROPERTY_PACKAGES,
    ContainerRequest.JSON_PROPERTY_SCAN_MODE,
    ContainerRequest.JSON_PROPERTY_SCAN_LEVELS,
    ContainerRequest.JSON_PROPERTY_TIMESTAMP,
    ContainerRequest.JSON_PROPERTY_TOWER_ACCESS_TOKEN,
    ContainerRequest.JSON_PROPERTY_TOWER_ENDPOINT,
    ContainerRequest.JSON_PROPERTY_TOWER_REFRESH_TOKEN,
    ContainerRequest.JSON_PROPERTY_TOWER_WORKSPACE_ID,
    ContainerRequest.JSON_PROPERTY_WORKFLOW_ID,
    ContainerRequest.JSON_PROPERTY_BUILD_TEMPLATE,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ContainerRequest {

    public static final String JSON_PROPERTY_CONTAINER_PLATFORM = "containerPlatform";
    public static final String JSON_PROPERTY_FORMAT = "format";
    public static final String JSON_PROPERTY_BUILD_CONTEXT = "buildContext";
    public static final String JSON_PROPERTY_BUILD_REPOSITORY = "buildRepository";
    public static final String JSON_PROPERTY_CACHE_REPOSITORY = "cacheRepository";
    public static final String JSON_PROPERTY_CONTAINER_CONFIG = "containerConfig";
    public static final String JSON_PROPERTY_CONTAINER_FILE = "containerFile";
    public static final String JSON_PROPERTY_CONTAINER_IMAGE = "containerImage";
    public static final String JSON_PROPERTY_CONTAINER_INCLUDES = "containerIncludes";
    public static final String JSON_PROPERTY_DRY_RUN = "dryRun";
    public static final String JSON_PROPERTY_FINGERPRINT = "fingerprint";
    public static final String JSON_PROPERTY_FREEZE = "freeze";
    public static final String JSON_PROPERTY_NAME_STRATEGY = "nameStrategy";
    public static final String JSON_PROPERTY_MIRROR = "mirror";
    public static final String JSON_PROPERTY_PACKAGES = "packages";
    public static final String JSON_PROPERTY_SCAN_MODE = "scanMode";
    public static final String JSON_PROPERTY_SCAN_LEVELS = "scanLevels";
    public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
    public static final String JSON_PROPERTY_TOWER_ACCESS_TOKEN = "towerAccessToken";
    public static final String JSON_PROPERTY_TOWER_ENDPOINT = "towerEndpoint";
    public static final String JSON_PROPERTY_TOWER_REFRESH_TOKEN = "towerRefreshToken";
    public static final String JSON_PROPERTY_TOWER_WORKSPACE_ID = "towerWorkspaceId";
    public static final String JSON_PROPERTY_WORKFLOW_ID = "workflowId";
    public static final String JSON_PROPERTY_BUILD_TEMPLATE = "buildTemplate";

    /**
     * Target container architecture of the built container, e.g., &#x60;linux/amd64&#x60; (optional). Currently only supporting amd64 and arm64.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_CONTAINER_PLATFORM)
    private String containerPlatform;

    @NotNull
    @JsonProperty(JSON_PROPERTY_FORMAT)
    private ContainerRequestFormat format;

    @Nullable(inherited = true)
    @Valid
    @JsonProperty(JSON_PROPERTY_BUILD_CONTEXT)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private ContainerLayer buildContext;

    /**
     * Container repository where container builds should be pushed, e.g., &#x60;docker.io/user/my-image&#x60; (optional).
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_BUILD_REPOSITORY)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String buildRepository;

    /**
     * Container repository used to cache build layers &#x60;docker.io/user/my-cache&#x60; (optional).
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_CACHE_REPOSITORY)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String cacheRepository;

    @Nullable(inherited = true)
    @Valid
    @JsonProperty(JSON_PROPERTY_CONTAINER_CONFIG)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private ContainerConfig containerConfig;

    /**
     * Dockerfile used for building a new container encoded in base64 (optional). When provided, the attribute &#x60;containerImage&#x60; must be omitted.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_CONTAINER_FILE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String containerFile;

    /**
     * Name of the container to be served, e.g., &#x60;docker.io/library/ubuntu:latest&#x60; (optional). If omitted, the &#x60;containerFile&#x60; must be provided.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_CONTAINER_IMAGE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String containerImage;

    /**
     * List of container images to include in the built container (optional).
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_CONTAINER_INCLUDES)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private List<@NotNull String> containerIncludes;

    /**
     * Request to build the container in a dry-run mode.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_DRY_RUN)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Boolean dryRun;

    /**
     * Request unique fingerprint.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_FINGERPRINT)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String fingerprint;

    /**
     * Freeze requires buildRepository to push the build container to a user-defined repository. This provides the container URL from the user-defined repository, not the Wave generated URL. This URL won&#39;t change.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_FREEZE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Boolean freeze;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_NAME_STRATEGY)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private ContainerRequestNameStrategy nameStrategy;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_MIRROR)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Boolean mirror;

    /**
     * Packages to be installed in the container.
     */
    @Nullable(inherited = true)
    @Valid
    @JsonProperty(JSON_PROPERTY_PACKAGES)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private PackagesSpec packages;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_SCAN_MODE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private ScanMode scanMode;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_SCAN_LEVELS)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private List<ScanLevel> scanLevels;

    /**
     * Request submission timestamp using ISO-8601.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TIMESTAMP)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String timestamp;

    /**
     * Access token of the user account granting access to the Seqera Platform service specified via &#x60;towerEndpoint&#x60; (optional).
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TOWER_ACCESS_TOKEN)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String towerAccessToken;

    /**
     * Seqera Platform service endpoint from where container registry credentials are retrieved (optional). Default &#x60;https://api.cloud.seqera.io&#x60;.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TOWER_ENDPOINT)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String towerEndpoint;

    /**
     * Token to refresh &#x60;&#x60;towerAccessToken&#x60; after it become invalid (optional).
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TOWER_REFRESH_TOKEN)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String towerRefreshToken;

    /**
     * ID of the Seqera Platform workspace from where the container registry credentials are retrieved (optional). When omitted the personal workspace is used.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TOWER_WORKSPACE_ID)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Long towerWorkspaceId;

    /**
     * ID of the Seqera Platform workspace from which this container request originates (optional).
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_WORKFLOW_ID)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String workflowId;

    /**
     * The build template that should be used to build the container image. Supported templates: - &#39;conda-pixi/v1&#39;: Uses Pixi package manager for modern, reproducible conda environments with multi-stage builds - &#39;conda-micromamba/v2&#39;: Uses Micromamba 2.x with multi-stage builds for optimized conda environments - Default: Uses standard conda/micromamba v1 template when not specified
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_BUILD_TEMPLATE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String buildTemplate;

    /**
     * Target container architecture of the built container, e.g., &#x60;linux/amd64&#x60; (optional). Currently only supporting amd64 and arm64.
     *
     * @return the containerPlatform property value
     */
    public String getContainerPlatform() {
        return containerPlatform;
    }

    /**
     * Set the containerPlatform property value
     *
     * @param containerPlatform property value to set
     */
    public void setContainerPlatform(String containerPlatform) {
        this.containerPlatform = containerPlatform;
    }

    /**
     * Set containerPlatform in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest containerPlatform(String containerPlatform) {
        this.containerPlatform = containerPlatform;
        return this;
    }

    /**
     * @return the format property value
     */
    public ContainerRequestFormat getFormat() {
        return format;
    }

    /**
     * Set the format property value
     *
     * @param format property value to set
     */
    public void setFormat(ContainerRequestFormat format) {
        this.format = format;
    }

    /**
     * Set format in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest format(ContainerRequestFormat format) {
        this.format = format;
        return this;
    }

    /**
     * @return the buildContext property value
     */
    public ContainerLayer getBuildContext() {
        return buildContext;
    }

    /**
     * Set the buildContext property value
     *
     * @param buildContext property value to set
     */
    public void setBuildContext(ContainerLayer buildContext) {
        this.buildContext = buildContext;
    }

    /**
     * Set buildContext in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest buildContext(ContainerLayer buildContext) {
        this.buildContext = buildContext;
        return this;
    }

    /**
     * Container repository where container builds should be pushed, e.g., &#x60;docker.io/user/my-image&#x60; (optional).
     *
     * @return the buildRepository property value
     */
    public String getBuildRepository() {
        return buildRepository;
    }

    /**
     * Set the buildRepository property value
     *
     * @param buildRepository property value to set
     */
    public void setBuildRepository(String buildRepository) {
        this.buildRepository = buildRepository;
    }

    /**
     * Set buildRepository in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest buildRepository(String buildRepository) {
        this.buildRepository = buildRepository;
        return this;
    }

    /**
     * Container repository used to cache build layers &#x60;docker.io/user/my-cache&#x60; (optional).
     *
     * @return the cacheRepository property value
     */
    public String getCacheRepository() {
        return cacheRepository;
    }

    /**
     * Set the cacheRepository property value
     *
     * @param cacheRepository property value to set
     */
    public void setCacheRepository(String cacheRepository) {
        this.cacheRepository = cacheRepository;
    }

    /**
     * Set cacheRepository in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest cacheRepository(String cacheRepository) {
        this.cacheRepository = cacheRepository;
        return this;
    }

    /**
     * @return the containerConfig property value
     */
    public ContainerConfig getContainerConfig() {
        return containerConfig;
    }

    /**
     * Set the containerConfig property value
     *
     * @param containerConfig property value to set
     */
    public void setContainerConfig(ContainerConfig containerConfig) {
        this.containerConfig = containerConfig;
    }

    /**
     * Set containerConfig in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest containerConfig(ContainerConfig containerConfig) {
        this.containerConfig = containerConfig;
        return this;
    }

    /**
     * Dockerfile used for building a new container encoded in base64 (optional). When provided, the attribute &#x60;containerImage&#x60; must be omitted.
     *
     * @return the containerFile property value
     */
    public String getContainerFile() {
        return containerFile;
    }

    /**
     * Set the containerFile property value
     *
     * @param containerFile property value to set
     */
    public void setContainerFile(String containerFile) {
        this.containerFile = containerFile;
    }

    /**
     * Set containerFile in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest containerFile(String containerFile) {
        this.containerFile = containerFile;
        return this;
    }

    /**
     * Name of the container to be served, e.g., &#x60;docker.io/library/ubuntu:latest&#x60; (optional). If omitted, the &#x60;containerFile&#x60; must be provided.
     *
     * @return the containerImage property value
     */
    public String getContainerImage() {
        return containerImage;
    }

    /**
     * Set the containerImage property value
     *
     * @param containerImage property value to set
     */
    public void setContainerImage(String containerImage) {
        this.containerImage = containerImage;
    }

    /**
     * Set containerImage in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest containerImage(String containerImage) {
        this.containerImage = containerImage;
        return this;
    }

    /**
     * List of container images to include in the built container (optional).
     *
     * @return the containerIncludes property value
     */
    public List<@NotNull String> getContainerIncludes() {
        return containerIncludes;
    }

    /**
     * Set the containerIncludes property value
     *
     * @param containerIncludes property value to set
     */
    public void setContainerIncludes(List<@NotNull String> containerIncludes) {
        this.containerIncludes = containerIncludes;
    }

    /**
     * Set containerIncludes in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest containerIncludes(List<@NotNull String> containerIncludes) {
        this.containerIncludes = containerIncludes;
        return this;
    }
    /**
     * Add an item to the containerIncludes property in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest addContainerIncludesItem(String containerIncludesItem) {
        if (containerIncludes == null) {
            containerIncludes = new ArrayList<>();
        }
        containerIncludes.add(containerIncludesItem);
        return this;
    }

    /**
     * Request to build the container in a dry-run mode.
     *
     * @return the dryRun property value
     */
    public Boolean getDryRun() {
        return dryRun;
    }

    /**
     * Set the dryRun property value
     *
     * @param dryRun property value to set
     */
    public void setDryRun(Boolean dryRun) {
        this.dryRun = dryRun;
    }

    /**
     * Set dryRun in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest dryRun(Boolean dryRun) {
        this.dryRun = dryRun;
        return this;
    }

    /**
     * Request unique fingerprint.
     *
     * @return the fingerprint property value
     */
    public String getFingerprint() {
        return fingerprint;
    }

    /**
     * Set the fingerprint property value
     *
     * @param fingerprint property value to set
     */
    public void setFingerprint(String fingerprint) {
        this.fingerprint = fingerprint;
    }

    /**
     * Set fingerprint in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest fingerprint(String fingerprint) {
        this.fingerprint = fingerprint;
        return this;
    }

    /**
     * Freeze requires buildRepository to push the build container to a user-defined repository. This provides the container URL from the user-defined repository, not the Wave generated URL. This URL won&#39;t change.
     *
     * @return the freeze property value
     */
    public Boolean getFreeze() {
        return freeze;
    }

    /**
     * Set the freeze property value
     *
     * @param freeze property value to set
     */
    public void setFreeze(Boolean freeze) {
        this.freeze = freeze;
    }

    /**
     * Set freeze in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest freeze(Boolean freeze) {
        this.freeze = freeze;
        return this;
    }

    /**
     * @return the nameStrategy property value
     */
    public ContainerRequestNameStrategy getNameStrategy() {
        return nameStrategy;
    }

    /**
     * Set the nameStrategy property value
     *
     * @param nameStrategy property value to set
     */
    public void setNameStrategy(ContainerRequestNameStrategy nameStrategy) {
        this.nameStrategy = nameStrategy;
    }

    /**
     * Set nameStrategy in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest nameStrategy(ContainerRequestNameStrategy nameStrategy) {
        this.nameStrategy = nameStrategy;
        return this;
    }

    /**
     * @return the mirror property value
     */
    public Boolean getMirror() {
        return mirror;
    }

    /**
     * Set the mirror property value
     *
     * @param mirror property value to set
     */
    public void setMirror(Boolean mirror) {
        this.mirror = mirror;
    }

    /**
     * Set mirror in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest mirror(Boolean mirror) {
        this.mirror = mirror;
        return this;
    }

    /**
     * Packages to be installed in the container.
     *
     * @return the packages property value
     */
    public PackagesSpec getPackages() {
        return packages;
    }

    /**
     * Set the packages property value
     *
     * @param packages property value to set
     */
    public void setPackages(PackagesSpec packages) {
        this.packages = packages;
    }

    /**
     * Set packages in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest packages(PackagesSpec packages) {
        this.packages = packages;
        return this;
    }

    /**
     * @return the scanMode property value
     */
    public ScanMode getScanMode() {
        return scanMode;
    }

    /**
     * Set the scanMode property value
     *
     * @param scanMode property value to set
     */
    public void setScanMode(ScanMode scanMode) {
        this.scanMode = scanMode;
    }

    /**
     * Set scanMode in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest scanMode(ScanMode scanMode) {
        this.scanMode = scanMode;
        return this;
    }

    /**
     * @return the scanLevels property value
     */
    public List<ScanLevel> getScanLevels() {
        return scanLevels;
    }

    /**
     * Set the scanLevels property value
     *
     * @param scanLevels property value to set
     */
    public void setScanLevels(List<ScanLevel> scanLevels) {
        this.scanLevels = scanLevels;
    }

    /**
     * Set scanLevels in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest scanLevels(List<ScanLevel> scanLevels) {
        this.scanLevels = scanLevels;
        return this;
    }
    /**
     * Add an item to the scanLevels property in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest addScanLevelsItem(ScanLevel scanLevelsItem) {
        if (scanLevels == null) {
            scanLevels = new ArrayList<>();
        }
        scanLevels.add(scanLevelsItem);
        return this;
    }

    /**
     * Request submission timestamp using ISO-8601.
     *
     * @return the timestamp property value
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Set the timestamp property value
     *
     * @param timestamp property value to set
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Set timestamp in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest timestamp(String timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    /**
     * Access token of the user account granting access to the Seqera Platform service specified via &#x60;towerEndpoint&#x60; (optional).
     *
     * @return the towerAccessToken property value
     */
    public String getTowerAccessToken() {
        return towerAccessToken;
    }

    /**
     * Set the towerAccessToken property value
     *
     * @param towerAccessToken property value to set
     */
    public void setTowerAccessToken(String towerAccessToken) {
        this.towerAccessToken = towerAccessToken;
    }

    /**
     * Set towerAccessToken in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest towerAccessToken(String towerAccessToken) {
        this.towerAccessToken = towerAccessToken;
        return this;
    }

    /**
     * Seqera Platform service endpoint from where container registry credentials are retrieved (optional). Default &#x60;https://api.cloud.seqera.io&#x60;.
     *
     * @return the towerEndpoint property value
     */
    public String getTowerEndpoint() {
        return towerEndpoint;
    }

    /**
     * Set the towerEndpoint property value
     *
     * @param towerEndpoint property value to set
     */
    public void setTowerEndpoint(String towerEndpoint) {
        this.towerEndpoint = towerEndpoint;
    }

    /**
     * Set towerEndpoint in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest towerEndpoint(String towerEndpoint) {
        this.towerEndpoint = towerEndpoint;
        return this;
    }

    /**
     * Token to refresh &#x60;&#x60;towerAccessToken&#x60; after it become invalid (optional).
     *
     * @return the towerRefreshToken property value
     */
    public String getTowerRefreshToken() {
        return towerRefreshToken;
    }

    /**
     * Set the towerRefreshToken property value
     *
     * @param towerRefreshToken property value to set
     */
    public void setTowerRefreshToken(String towerRefreshToken) {
        this.towerRefreshToken = towerRefreshToken;
    }

    /**
     * Set towerRefreshToken in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest towerRefreshToken(String towerRefreshToken) {
        this.towerRefreshToken = towerRefreshToken;
        return this;
    }

    /**
     * ID of the Seqera Platform workspace from where the container registry credentials are retrieved (optional). When omitted the personal workspace is used.
     *
     * @return the towerWorkspaceId property value
     */
    public Long getTowerWorkspaceId() {
        return towerWorkspaceId;
    }

    /**
     * Set the towerWorkspaceId property value
     *
     * @param towerWorkspaceId property value to set
     */
    public void setTowerWorkspaceId(Long towerWorkspaceId) {
        this.towerWorkspaceId = towerWorkspaceId;
    }

    /**
     * Set towerWorkspaceId in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest towerWorkspaceId(Long towerWorkspaceId) {
        this.towerWorkspaceId = towerWorkspaceId;
        return this;
    }

    /**
     * ID of the Seqera Platform workspace from which this container request originates (optional).
     *
     * @return the workflowId property value
     */
    public String getWorkflowId() {
        return workflowId;
    }

    /**
     * Set the workflowId property value
     *
     * @param workflowId property value to set
     */
    public void setWorkflowId(String workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * Set workflowId in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest workflowId(String workflowId) {
        this.workflowId = workflowId;
        return this;
    }

    /**
     * The build template that should be used to build the container image. Supported templates: - &#39;conda-pixi/v1&#39;: Uses Pixi package manager for modern, reproducible conda environments with multi-stage builds - &#39;conda-micromamba/v2&#39;: Uses Micromamba 2.x with multi-stage builds for optimized conda environments - Default: Uses standard conda/micromamba v1 template when not specified
     *
     * @return the buildTemplate property value
     */
    public String getBuildTemplate() {
        return buildTemplate;
    }

    /**
     * Set the buildTemplate property value
     *
     * @param buildTemplate property value to set
     */
    public void setBuildTemplate(String buildTemplate) {
        this.buildTemplate = buildTemplate;
    }

    /**
     * Set buildTemplate in a chainable fashion.
     *
     * @return The same instance of ContainerRequest for chaining.
     */
    public ContainerRequest buildTemplate(String buildTemplate) {
        this.buildTemplate = buildTemplate;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var containerRequest = (ContainerRequest) o;
        return Objects.equals(containerPlatform, containerRequest.containerPlatform)
            && Objects.equals(format, containerRequest.format)
            && Objects.equals(buildContext, containerRequest.buildContext)
            && Objects.equals(buildRepository, containerRequest.buildRepository)
            && Objects.equals(cacheRepository, containerRequest.cacheRepository)
            && Objects.equals(containerConfig, containerRequest.containerConfig)
            && Objects.equals(containerFile, containerRequest.containerFile)
            && Objects.equals(containerImage, containerRequest.containerImage)
            && Objects.equals(containerIncludes, containerRequest.containerIncludes)
            && Objects.equals(dryRun, containerRequest.dryRun)
            && Objects.equals(fingerprint, containerRequest.fingerprint)
            && Objects.equals(freeze, containerRequest.freeze)
            && Objects.equals(nameStrategy, containerRequest.nameStrategy)
            && Objects.equals(mirror, containerRequest.mirror)
            && Objects.equals(packages, containerRequest.packages)
            && Objects.equals(scanMode, containerRequest.scanMode)
            && Objects.equals(scanLevels, containerRequest.scanLevels)
            && Objects.equals(timestamp, containerRequest.timestamp)
            && Objects.equals(towerAccessToken, containerRequest.towerAccessToken)
            && Objects.equals(towerEndpoint, containerRequest.towerEndpoint)
            && Objects.equals(towerRefreshToken, containerRequest.towerRefreshToken)
            && Objects.equals(towerWorkspaceId, containerRequest.towerWorkspaceId)
            && Objects.equals(workflowId, containerRequest.workflowId)
            && Objects.equals(buildTemplate, containerRequest.buildTemplate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(containerPlatform, format, buildContext, buildRepository, cacheRepository, containerConfig, containerFile, containerImage, containerIncludes, dryRun, fingerprint, freeze, nameStrategy, mirror, packages, scanMode, scanLevels, timestamp, towerAccessToken, towerEndpoint, towerRefreshToken, towerWorkspaceId, workflowId, buildTemplate);
    }

    @Override
    public String toString() {
        return "ContainerRequest("
            + "containerPlatform: " + getContainerPlatform() + ", "
            + "format: " + getFormat() + ", "
            + "buildContext: " + getBuildContext() + ", "
            + "buildRepository: " + getBuildRepository() + ", "
            + "cacheRepository: " + getCacheRepository() + ", "
            + "containerConfig: " + getContainerConfig() + ", "
            + "containerFile: " + getContainerFile() + ", "
            + "containerImage: " + getContainerImage() + ", "
            + "containerIncludes: " + getContainerIncludes() + ", "
            + "dryRun: " + getDryRun() + ", "
            + "fingerprint: " + getFingerprint() + ", "
            + "freeze: " + getFreeze() + ", "
            + "nameStrategy: " + getNameStrategy() + ", "
            + "mirror: " + getMirror() + ", "
            + "packages: " + getPackages() + ", "
            + "scanMode: " + getScanMode() + ", "
            + "scanLevels: " + getScanLevels() + ", "
            + "timestamp: " + getTimestamp() + ", "
            + "towerAccessToken: " + getTowerAccessToken() + ", "
            + "towerEndpoint: " + getTowerEndpoint() + ", "
            + "towerRefreshToken: " + getTowerRefreshToken() + ", "
            + "towerWorkspaceId: " + getTowerWorkspaceId() + ", "
            + "workflowId: " + getWorkflowId() + ", "
            + "buildTemplate: " + getBuildTemplate()
            + ")";
    }

}