/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * ContainerInspectConfigConfig
 */
@Serdeable
@JsonPropertyOrder({
    ContainerInspectConfigConfig.JSON_PROPERTY_ATTACH_STDIN,
    ContainerInspectConfigConfig.JSON_PROPERTY_ATTACH_STDOUT,
    ContainerInspectConfigConfig.JSON_PROPERTY_ATTACH_STDERR,
    ContainerInspectConfigConfig.JSON_PROPERTY_TTY,
    ContainerInspectConfigConfig.JSON_PROPERTY_ENV,
    ContainerInspectConfigConfig.JSON_PROPERTY_CMD,
    ContainerInspectConfigConfig.JSON_PROPERTY_IMAGE,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ContainerInspectConfigConfig {

    public static final String JSON_PROPERTY_ATTACH_STDIN = "attachStdin";
    public static final String JSON_PROPERTY_ATTACH_STDOUT = "attachStdout";
    public static final String JSON_PROPERTY_ATTACH_STDERR = "attachStderr";
    public static final String JSON_PROPERTY_TTY = "tty";
    public static final String JSON_PROPERTY_ENV = "env";
    public static final String JSON_PROPERTY_CMD = "cmd";
    public static final String JSON_PROPERTY_IMAGE = "image";

    @NotNull
    @JsonProperty(JSON_PROPERTY_ATTACH_STDIN)
    private Boolean attachStdin;

    @NotNull
    @JsonProperty(JSON_PROPERTY_ATTACH_STDOUT)
    private Boolean attachStdout;

    @NotNull
    @JsonProperty(JSON_PROPERTY_ATTACH_STDERR)
    private Boolean attachStderr;

    @NotNull
    @JsonProperty(JSON_PROPERTY_TTY)
    private Boolean tty;

    @NotNull
    @JsonProperty(JSON_PROPERTY_ENV)
    private List<@NotNull String> env = new ArrayList<>();

    @NotNull
    @JsonProperty(JSON_PROPERTY_CMD)
    private List<@NotNull String> cmd = new ArrayList<>();

    @NotNull
    @JsonProperty(JSON_PROPERTY_IMAGE)
    private String image;

    /**
     * @return the attachStdin property value
     */
    public Boolean getAttachStdin() {
        return attachStdin;
    }

    /**
     * Set the attachStdin property value
     *
     * @param attachStdin property value to set
     */
    public void setAttachStdin(Boolean attachStdin) {
        this.attachStdin = attachStdin;
    }

    /**
     * Set attachStdin in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfigConfig for chaining.
     */
    public ContainerInspectConfigConfig attachStdin(Boolean attachStdin) {
        this.attachStdin = attachStdin;
        return this;
    }

    /**
     * @return the attachStdout property value
     */
    public Boolean getAttachStdout() {
        return attachStdout;
    }

    /**
     * Set the attachStdout property value
     *
     * @param attachStdout property value to set
     */
    public void setAttachStdout(Boolean attachStdout) {
        this.attachStdout = attachStdout;
    }

    /**
     * Set attachStdout in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfigConfig for chaining.
     */
    public ContainerInspectConfigConfig attachStdout(Boolean attachStdout) {
        this.attachStdout = attachStdout;
        return this;
    }

    /**
     * @return the attachStderr property value
     */
    public Boolean getAttachStderr() {
        return attachStderr;
    }

    /**
     * Set the attachStderr property value
     *
     * @param attachStderr property value to set
     */
    public void setAttachStderr(Boolean attachStderr) {
        this.attachStderr = attachStderr;
    }

    /**
     * Set attachStderr in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfigConfig for chaining.
     */
    public ContainerInspectConfigConfig attachStderr(Boolean attachStderr) {
        this.attachStderr = attachStderr;
        return this;
    }

    /**
     * @return the tty property value
     */
    public Boolean getTty() {
        return tty;
    }

    /**
     * Set the tty property value
     *
     * @param tty property value to set
     */
    public void setTty(Boolean tty) {
        this.tty = tty;
    }

    /**
     * Set tty in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfigConfig for chaining.
     */
    public ContainerInspectConfigConfig tty(Boolean tty) {
        this.tty = tty;
        return this;
    }

    /**
     * @return the env property value
     */
    public List<@NotNull String> getEnv() {
        return env;
    }

    /**
     * Set the env property value
     *
     * @param env property value to set
     */
    public void setEnv(List<@NotNull String> env) {
        this.env = env;
    }

    /**
     * Set env in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfigConfig for chaining.
     */
    public ContainerInspectConfigConfig env(List<@NotNull String> env) {
        this.env = env;
        return this;
    }
    /**
     * Add an item to the env property in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfigConfig for chaining.
     */
    public ContainerInspectConfigConfig addEnvItem(String envItem) {
        env.add(envItem);
        return this;
    }

    /**
     * @return the cmd property value
     */
    public List<@NotNull String> getCmd() {
        return cmd;
    }

    /**
     * Set the cmd property value
     *
     * @param cmd property value to set
     */
    public void setCmd(List<@NotNull String> cmd) {
        this.cmd = cmd;
    }

    /**
     * Set cmd in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfigConfig for chaining.
     */
    public ContainerInspectConfigConfig cmd(List<@NotNull String> cmd) {
        this.cmd = cmd;
        return this;
    }
    /**
     * Add an item to the cmd property in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfigConfig for chaining.
     */
    public ContainerInspectConfigConfig addCmdItem(String cmdItem) {
        cmd.add(cmdItem);
        return this;
    }

    /**
     * @return the image property value
     */
    public String getImage() {
        return image;
    }

    /**
     * Set the image property value
     *
     * @param image property value to set
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * Set image in a chainable fashion.
     *
     * @return The same instance of ContainerInspectConfigConfig for chaining.
     */
    public ContainerInspectConfigConfig image(String image) {
        this.image = image;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var containerInspectConfigConfig = (ContainerInspectConfigConfig) o;
        return Objects.equals(attachStdin, containerInspectConfigConfig.attachStdin)
            && Objects.equals(attachStdout, containerInspectConfigConfig.attachStdout)
            && Objects.equals(attachStderr, containerInspectConfigConfig.attachStderr)
            && Objects.equals(tty, containerInspectConfigConfig.tty)
            && Objects.equals(env, containerInspectConfigConfig.env)
            && Objects.equals(cmd, containerInspectConfigConfig.cmd)
            && Objects.equals(image, containerInspectConfigConfig.image);
    }

    @Override
    public int hashCode() {
        return Objects.hash(attachStdin, attachStdout, attachStderr, tty, env, cmd, image);
    }

    @Override
    public String toString() {
        return "ContainerInspectConfigConfig("
            + "attachStdin: " + getAttachStdin() + ", "
            + "attachStdout: " + getAttachStdout() + ", "
            + "attachStderr: " + getAttachStderr() + ", "
            + "tty: " + getTty() + ", "
            + "env: " + getEnv() + ", "
            + "cmd: " + getCmd() + ", "
            + "image: " + getImage()
            + ")";
    }

}