/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Represents os platform of a container.
 */
@Serdeable
@JsonPropertyOrder({
    ContainerPlatform.JSON_PROPERTY_OS,
    ContainerPlatform.JSON_PROPERTY_ARCH,
    ContainerPlatform.JSON_PROPERTY_VARIANT,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ContainerPlatform {

    public static final String JSON_PROPERTY_OS = "os";
    public static final String JSON_PROPERTY_ARCH = "arch";
    public static final String JSON_PROPERTY_VARIANT = "variant";

    @NotNull
    @JsonProperty(JSON_PROPERTY_OS)
    private String os;

    @NotNull
    @JsonProperty(JSON_PROPERTY_ARCH)
    private String arch;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_VARIANT)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String variant;

    /**
     * @return the os property value
     */
    public String getOs() {
        return os;
    }

    /**
     * Set the os property value
     *
     * @param os property value to set
     */
    public void setOs(String os) {
        this.os = os;
    }

    /**
     * Set os in a chainable fashion.
     *
     * @return The same instance of ContainerPlatform for chaining.
     */
    public ContainerPlatform os(String os) {
        this.os = os;
        return this;
    }

    /**
     * @return the arch property value
     */
    public String getArch() {
        return arch;
    }

    /**
     * Set the arch property value
     *
     * @param arch property value to set
     */
    public void setArch(String arch) {
        this.arch = arch;
    }

    /**
     * Set arch in a chainable fashion.
     *
     * @return The same instance of ContainerPlatform for chaining.
     */
    public ContainerPlatform arch(String arch) {
        this.arch = arch;
        return this;
    }

    /**
     * @return the variant property value
     */
    public String getVariant() {
        return variant;
    }

    /**
     * Set the variant property value
     *
     * @param variant property value to set
     */
    public void setVariant(String variant) {
        this.variant = variant;
    }

    /**
     * Set variant in a chainable fashion.
     *
     * @return The same instance of ContainerPlatform for chaining.
     */
    public ContainerPlatform variant(String variant) {
        this.variant = variant;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var containerPlatform = (ContainerPlatform) o;
        return Objects.equals(os, containerPlatform.os)
            && Objects.equals(arch, containerPlatform.arch)
            && Objects.equals(variant, containerPlatform.variant);
    }

    @Override
    public int hashCode() {
        return Objects.hash(os, arch, variant);
    }

    @Override
    public String toString() {
        return "ContainerPlatform("
            + "os: " + getOs() + ", "
            + "arch: " + getArch() + ", "
            + "variant: " + getVariant()
            + ")";
    }

}