/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Represents a layer in a container image.
 */
@Serdeable
@JsonPropertyOrder({
    ContainerLayer.JSON_PROPERTY_GZIP_DIGEST,
    ContainerLayer.JSON_PROPERTY_GZIP_SIZE,
    ContainerLayer.JSON_PROPERTY_LOCATION,
    ContainerLayer.JSON_PROPERTY_SKIP_HASHING,
    ContainerLayer.JSON_PROPERTY_TAR_DIGEST,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ContainerLayer {

    public static final String JSON_PROPERTY_GZIP_DIGEST = "gzipDigest";
    public static final String JSON_PROPERTY_GZIP_SIZE = "gzipSize";
    public static final String JSON_PROPERTY_LOCATION = "location";
    public static final String JSON_PROPERTY_SKIP_HASHING = "skipHashing";
    public static final String JSON_PROPERTY_TAR_DIGEST = "tarDigest";

    /**
     * The SHA256 checksum of the provided layer tar gzip file, e.g., &#x60;sha256:a7c724b02...&#x60;.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_GZIP_DIGEST)
    private String gzipDigest;

    /**
     * The size in bytes of the the provided layer tar gzip file.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_GZIP_SIZE)
    private String gzipSize;

    /**
     * Specifies a container image layer stored as a tar.gz file (optional). Either a HTTP URL to the file or a base64 encoded string prefixed with &#x60;data:&#x60;.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_LOCATION)
    private String location;

    /**
     * If true, the layer tar file will not be hashed.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_SKIP_HASHING)
    private Boolean skipHashing;

    /**
     * The SHA256checksum of the provided tar file, e.g., &#x60;sha256:a7c724b02...&#x60;.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_TAR_DIGEST)
    private String tarDigest;

    /**
     * The SHA256 checksum of the provided layer tar gzip file, e.g., &#x60;sha256:a7c724b02...&#x60;.
     *
     * @return the gzipDigest property value
     */
    public String getGzipDigest() {
        return gzipDigest;
    }

    /**
     * Set the gzipDigest property value
     *
     * @param gzipDigest property value to set
     */
    public void setGzipDigest(String gzipDigest) {
        this.gzipDigest = gzipDigest;
    }

    /**
     * Set gzipDigest in a chainable fashion.
     *
     * @return The same instance of ContainerLayer for chaining.
     */
    public ContainerLayer gzipDigest(String gzipDigest) {
        this.gzipDigest = gzipDigest;
        return this;
    }

    /**
     * The size in bytes of the the provided layer tar gzip file.
     *
     * @return the gzipSize property value
     */
    public String getGzipSize() {
        return gzipSize;
    }

    /**
     * Set the gzipSize property value
     *
     * @param gzipSize property value to set
     */
    public void setGzipSize(String gzipSize) {
        this.gzipSize = gzipSize;
    }

    /**
     * Set gzipSize in a chainable fashion.
     *
     * @return The same instance of ContainerLayer for chaining.
     */
    public ContainerLayer gzipSize(String gzipSize) {
        this.gzipSize = gzipSize;
        return this;
    }

    /**
     * Specifies a container image layer stored as a tar.gz file (optional). Either a HTTP URL to the file or a base64 encoded string prefixed with &#x60;data:&#x60;.
     *
     * @return the location property value
     */
    public String getLocation() {
        return location;
    }

    /**
     * Set the location property value
     *
     * @param location property value to set
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * Set location in a chainable fashion.
     *
     * @return The same instance of ContainerLayer for chaining.
     */
    public ContainerLayer location(String location) {
        this.location = location;
        return this;
    }

    /**
     * If true, the layer tar file will not be hashed.
     *
     * @return the skipHashing property value
     */
    public Boolean getSkipHashing() {
        return skipHashing;
    }

    /**
     * Set the skipHashing property value
     *
     * @param skipHashing property value to set
     */
    public void setSkipHashing(Boolean skipHashing) {
        this.skipHashing = skipHashing;
    }

    /**
     * Set skipHashing in a chainable fashion.
     *
     * @return The same instance of ContainerLayer for chaining.
     */
    public ContainerLayer skipHashing(Boolean skipHashing) {
        this.skipHashing = skipHashing;
        return this;
    }

    /**
     * The SHA256checksum of the provided tar file, e.g., &#x60;sha256:a7c724b02...&#x60;.
     *
     * @return the tarDigest property value
     */
    public String getTarDigest() {
        return tarDigest;
    }

    /**
     * Set the tarDigest property value
     *
     * @param tarDigest property value to set
     */
    public void setTarDigest(String tarDigest) {
        this.tarDigest = tarDigest;
    }

    /**
     * Set tarDigest in a chainable fashion.
     *
     * @return The same instance of ContainerLayer for chaining.
     */
    public ContainerLayer tarDigest(String tarDigest) {
        this.tarDigest = tarDigest;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var containerLayer = (ContainerLayer) o;
        return Objects.equals(gzipDigest, containerLayer.gzipDigest)
            && Objects.equals(gzipSize, containerLayer.gzipSize)
            && Objects.equals(location, containerLayer.location)
            && Objects.equals(skipHashing, containerLayer.skipHashing)
            && Objects.equals(tarDigest, containerLayer.tarDigest);
    }

    @Override
    public int hashCode() {
        return Objects.hash(gzipDigest, gzipSize, location, skipHashing, tarDigest);
    }

    @Override
    public String toString() {
        return "ContainerLayer("
            + "gzipDigest: " + getGzipDigest() + ", "
            + "gzipSize: " + getGzipSize() + ", "
            + "location: " + getLocation() + ", "
            + "skipHashing: " + getSkipHashing() + ", "
            + "tarDigest: " + getTarDigest()
            + ")";
    }

}