/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.wave.api.v1.model.ContainerStatus;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Response payload for container token creation.
 */
@Serdeable
@JsonPropertyOrder({
    ContainerResponse.JSON_PROPERTY_BUILD_ID,
    ContainerResponse.JSON_PROPERTY_CACHED,
    ContainerResponse.JSON_PROPERTY_CONTAINER_IMAGE,
    ContainerResponse.JSON_PROPERTY_CONTAINER_TOKEN,
    ContainerResponse.JSON_PROPERTY_EXPIRATION,
    ContainerResponse.JSON_PROPERTY_FREEZE,
    ContainerResponse.JSON_PROPERTY_MIRROR,
    ContainerResponse.JSON_PROPERTY_REQUEST_ID,
    ContainerResponse.JSON_PROPERTY_SCAN_ID,
    ContainerResponse.JSON_PROPERTY_STATUS,
    ContainerResponse.JSON_PROPERTY_TARGET_IMAGE,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ContainerResponse {

    public static final String JSON_PROPERTY_BUILD_ID = "buildId";
    public static final String JSON_PROPERTY_CACHED = "cached";
    public static final String JSON_PROPERTY_CONTAINER_IMAGE = "containerImage";
    public static final String JSON_PROPERTY_CONTAINER_TOKEN = "containerToken";
    public static final String JSON_PROPERTY_EXPIRATION = "expiration";
    public static final String JSON_PROPERTY_FREEZE = "freeze";
    public static final String JSON_PROPERTY_MIRROR = "mirror";
    public static final String JSON_PROPERTY_REQUEST_ID = "requestId";
    public static final String JSON_PROPERTY_SCAN_ID = "scanId";
    public static final String JSON_PROPERTY_STATUS = "status";
    public static final String JSON_PROPERTY_TARGET_IMAGE = "targetImage";

    /**
     * Unique identifier for the build.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_BUILD_ID)
    private String buildId;

    /**
     * Indicates if the build is cached.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_CACHED)
    private Boolean cached;

    /**
     * Container image to be used.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_CONTAINER_IMAGE)
    private String containerImage;

    /**
     * Token to access the container.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_CONTAINER_TOKEN)
    private String containerToken;

    /**
     * The expiration timestamp of the Wave container using ISO-8601 format.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_EXPIRATION)
    private String expiration;

    /**
     * Indicates if the build is pushed to user container registry.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_FREEZE)
    private Boolean freeze;

    /**
     * Indicates if its a mirror request.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_MIRROR)
    private Boolean mirror;

    /**
     * Unique identifier for the request.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_REQUEST_ID)
    private String requestId;

    /**
     * Unique identifier for the scan.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_SCAN_ID)
    private String scanId;

    /**
     * Status of the container build.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_STATUS)
    private ContainerStatus status;

    /**
     * The Wave container image name
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_TARGET_IMAGE)
    private String targetImage;

    /**
     * Unique identifier for the build.
     *
     * @return the buildId property value
     */
    public String getBuildId() {
        return buildId;
    }

    /**
     * Set the buildId property value
     *
     * @param buildId property value to set
     */
    public void setBuildId(String buildId) {
        this.buildId = buildId;
    }

    /**
     * Set buildId in a chainable fashion.
     *
     * @return The same instance of ContainerResponse for chaining.
     */
    public ContainerResponse buildId(String buildId) {
        this.buildId = buildId;
        return this;
    }

    /**
     * Indicates if the build is cached.
     *
     * @return the cached property value
     */
    public Boolean getCached() {
        return cached;
    }

    /**
     * Set the cached property value
     *
     * @param cached property value to set
     */
    public void setCached(Boolean cached) {
        this.cached = cached;
    }

    /**
     * Set cached in a chainable fashion.
     *
     * @return The same instance of ContainerResponse for chaining.
     */
    public ContainerResponse cached(Boolean cached) {
        this.cached = cached;
        return this;
    }

    /**
     * Container image to be used.
     *
     * @return the containerImage property value
     */
    public String getContainerImage() {
        return containerImage;
    }

    /**
     * Set the containerImage property value
     *
     * @param containerImage property value to set
     */
    public void setContainerImage(String containerImage) {
        this.containerImage = containerImage;
    }

    /**
     * Set containerImage in a chainable fashion.
     *
     * @return The same instance of ContainerResponse for chaining.
     */
    public ContainerResponse containerImage(String containerImage) {
        this.containerImage = containerImage;
        return this;
    }

    /**
     * Token to access the container.
     *
     * @return the containerToken property value
     */
    public String getContainerToken() {
        return containerToken;
    }

    /**
     * Set the containerToken property value
     *
     * @param containerToken property value to set
     */
    public void setContainerToken(String containerToken) {
        this.containerToken = containerToken;
    }

    /**
     * Set containerToken in a chainable fashion.
     *
     * @return The same instance of ContainerResponse for chaining.
     */
    public ContainerResponse containerToken(String containerToken) {
        this.containerToken = containerToken;
        return this;
    }

    /**
     * The expiration timestamp of the Wave container using ISO-8601 format.
     *
     * @return the expiration property value
     */
    public String getExpiration() {
        return expiration;
    }

    /**
     * Set the expiration property value
     *
     * @param expiration property value to set
     */
    public void setExpiration(String expiration) {
        this.expiration = expiration;
    }

    /**
     * Set expiration in a chainable fashion.
     *
     * @return The same instance of ContainerResponse for chaining.
     */
    public ContainerResponse expiration(String expiration) {
        this.expiration = expiration;
        return this;
    }

    /**
     * Indicates if the build is pushed to user container registry.
     *
     * @return the freeze property value
     */
    public Boolean getFreeze() {
        return freeze;
    }

    /**
     * Set the freeze property value
     *
     * @param freeze property value to set
     */
    public void setFreeze(Boolean freeze) {
        this.freeze = freeze;
    }

    /**
     * Set freeze in a chainable fashion.
     *
     * @return The same instance of ContainerResponse for chaining.
     */
    public ContainerResponse freeze(Boolean freeze) {
        this.freeze = freeze;
        return this;
    }

    /**
     * Indicates if its a mirror request.
     *
     * @return the mirror property value
     */
    public Boolean getMirror() {
        return mirror;
    }

    /**
     * Set the mirror property value
     *
     * @param mirror property value to set
     */
    public void setMirror(Boolean mirror) {
        this.mirror = mirror;
    }

    /**
     * Set mirror in a chainable fashion.
     *
     * @return The same instance of ContainerResponse for chaining.
     */
    public ContainerResponse mirror(Boolean mirror) {
        this.mirror = mirror;
        return this;
    }

    /**
     * Unique identifier for the request.
     *
     * @return the requestId property value
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Set the requestId property value
     *
     * @param requestId property value to set
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * Set requestId in a chainable fashion.
     *
     * @return The same instance of ContainerResponse for chaining.
     */
    public ContainerResponse requestId(String requestId) {
        this.requestId = requestId;
        return this;
    }

    /**
     * Unique identifier for the scan.
     *
     * @return the scanId property value
     */
    public String getScanId() {
        return scanId;
    }

    /**
     * Set the scanId property value
     *
     * @param scanId property value to set
     */
    public void setScanId(String scanId) {
        this.scanId = scanId;
    }

    /**
     * Set scanId in a chainable fashion.
     *
     * @return The same instance of ContainerResponse for chaining.
     */
    public ContainerResponse scanId(String scanId) {
        this.scanId = scanId;
        return this;
    }

    /**
     * Status of the container build.
     *
     * @return the status property value
     */
    public ContainerStatus getStatus() {
        return status;
    }

    /**
     * Set the status property value
     *
     * @param status property value to set
     */
    public void setStatus(ContainerStatus status) {
        this.status = status;
    }

    /**
     * Set status in a chainable fashion.
     *
     * @return The same instance of ContainerResponse for chaining.
     */
    public ContainerResponse status(ContainerStatus status) {
        this.status = status;
        return this;
    }

    /**
     * The Wave container image name
     *
     * @return the targetImage property value
     */
    public String getTargetImage() {
        return targetImage;
    }

    /**
     * Set the targetImage property value
     *
     * @param targetImage property value to set
     */
    public void setTargetImage(String targetImage) {
        this.targetImage = targetImage;
    }

    /**
     * Set targetImage in a chainable fashion.
     *
     * @return The same instance of ContainerResponse for chaining.
     */
    public ContainerResponse targetImage(String targetImage) {
        this.targetImage = targetImage;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var containerResponse = (ContainerResponse) o;
        return Objects.equals(buildId, containerResponse.buildId)
            && Objects.equals(cached, containerResponse.cached)
            && Objects.equals(containerImage, containerResponse.containerImage)
            && Objects.equals(containerToken, containerResponse.containerToken)
            && Objects.equals(expiration, containerResponse.expiration)
            && Objects.equals(freeze, containerResponse.freeze)
            && Objects.equals(mirror, containerResponse.mirror)
            && Objects.equals(requestId, containerResponse.requestId)
            && Objects.equals(scanId, containerResponse.scanId)
            && Objects.equals(status, containerResponse.status)
            && Objects.equals(targetImage, containerResponse.targetImage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(buildId, cached, containerImage, containerToken, expiration, freeze, mirror, requestId, scanId, status, targetImage);
    }

    @Override
    public String toString() {
        return "ContainerResponse("
            + "buildId: " + getBuildId() + ", "
            + "cached: " + getCached() + ", "
            + "containerImage: " + getContainerImage() + ", "
            + "containerToken: " + getContainerToken() + ", "
            + "expiration: " + getExpiration() + ", "
            + "freeze: " + getFreeze() + ", "
            + "mirror: " + getMirror() + ", "
            + "requestId: " + getRequestId() + ", "
            + "scanId: " + getScanId() + ", "
            + "status: " + getStatus() + ", "
            + "targetImage: " + getTargetImage()
            + ")";
    }

}