/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Options for CRAN/R environments.
 */
@Serdeable
@JsonPropertyOrder({
    CranOpts.JSON_PROPERTY_RIMAGE,
    CranOpts.JSON_PROPERTY_BASE_PACKAGES,
    CranOpts.JSON_PROPERTY_COMMANDS,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class CranOpts {

    public static final String JSON_PROPERTY_RIMAGE = "rImage";
    public static final String JSON_PROPERTY_BASE_PACKAGES = "basePackages";
    public static final String JSON_PROPERTY_COMMANDS = "commands";

    /**
     * Name of the R Docker image used to build CRAN containers.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_RIMAGE)
    private String rimage;

    /**
     * Names of base system packages to install.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_BASE_PACKAGES)
    private String basePackages;

    /**
     * Commands to be included in the container.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_COMMANDS)
    private List<@NotNull String> commands = new ArrayList<>();

    /**
     * Name of the R Docker image used to build CRAN containers.
     *
     * @return the rimage property value
     */
    public String getRimage() {
        return rimage;
    }

    /**
     * Set the rimage property value
     *
     * @param rimage property value to set
     */
    public void setRimage(String rimage) {
        this.rimage = rimage;
    }

    /**
     * Set rimage in a chainable fashion.
     *
     * @return The same instance of CranOpts for chaining.
     */
    public CranOpts rimage(String rimage) {
        this.rimage = rimage;
        return this;
    }

    /**
     * Names of base system packages to install.
     *
     * @return the basePackages property value
     */
    public String getBasePackages() {
        return basePackages;
    }

    /**
     * Set the basePackages property value
     *
     * @param basePackages property value to set
     */
    public void setBasePackages(String basePackages) {
        this.basePackages = basePackages;
    }

    /**
     * Set basePackages in a chainable fashion.
     *
     * @return The same instance of CranOpts for chaining.
     */
    public CranOpts basePackages(String basePackages) {
        this.basePackages = basePackages;
        return this;
    }

    /**
     * Commands to be included in the container.
     *
     * @return the commands property value
     */
    public List<@NotNull String> getCommands() {
        return commands;
    }

    /**
     * Set the commands property value
     *
     * @param commands property value to set
     */
    public void setCommands(List<@NotNull String> commands) {
        this.commands = commands;
    }

    /**
     * Set commands in a chainable fashion.
     *
     * @return The same instance of CranOpts for chaining.
     */
    public CranOpts commands(List<@NotNull String> commands) {
        this.commands = commands;
        return this;
    }
    /**
     * Add an item to the commands property in a chainable fashion.
     *
     * @return The same instance of CranOpts for chaining.
     */
    public CranOpts addCommandsItem(String commandsItem) {
        commands.add(commandsItem);
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var cranOpts = (CranOpts) o;
        return Objects.equals(rimage, cranOpts.rimage)
            && Objects.equals(basePackages, cranOpts.basePackages)
            && Objects.equals(commands, cranOpts.commands);
    }

    @Override
    public int hashCode() {
        return Objects.hash(rimage, basePackages, commands);
    }

    @Override
    public String toString() {
        return "CranOpts("
            + "rimage: " + getRimage() + ", "
            + "basePackages: " + getBasePackages() + ", "
            + "commands: " + getCommands()
            + ")";
    }

}