/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * ManifestConfig
 */
@Serdeable
@JsonPropertyOrder({
    ManifestConfig.JSON_PROPERTY_DIGEST,
    ManifestConfig.JSON_PROPERTY_MEDIA_TYPE,
    ManifestConfig.JSON_PROPERTY_SIZE,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ManifestConfig {

    public static final String JSON_PROPERTY_DIGEST = "digest";
    public static final String JSON_PROPERTY_MEDIA_TYPE = "mediaType";
    public static final String JSON_PROPERTY_SIZE = "size";

    @NotNull
    @JsonProperty(JSON_PROPERTY_DIGEST)
    private String digest;

    @NotNull
    @JsonProperty(JSON_PROPERTY_MEDIA_TYPE)
    private String mediaType;

    @NotNull
    @JsonProperty(JSON_PROPERTY_SIZE)
    private Long size;

    /**
     * @return the digest property value
     */
    public String getDigest() {
        return digest;
    }

    /**
     * Set the digest property value
     *
     * @param digest property value to set
     */
    public void setDigest(String digest) {
        this.digest = digest;
    }

    /**
     * Set digest in a chainable fashion.
     *
     * @return The same instance of ManifestConfig for chaining.
     */
    public ManifestConfig digest(String digest) {
        this.digest = digest;
        return this;
    }

    /**
     * @return the mediaType property value
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * Set the mediaType property value
     *
     * @param mediaType property value to set
     */
    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * Set mediaType in a chainable fashion.
     *
     * @return The same instance of ManifestConfig for chaining.
     */
    public ManifestConfig mediaType(String mediaType) {
        this.mediaType = mediaType;
        return this;
    }

    /**
     * @return the size property value
     */
    public Long getSize() {
        return size;
    }

    /**
     * Set the size property value
     *
     * @param size property value to set
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * Set size in a chainable fashion.
     *
     * @return The same instance of ManifestConfig for chaining.
     */
    public ManifestConfig size(Long size) {
        this.size = size;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var manifestConfig = (ManifestConfig) o;
        return Objects.equals(digest, manifestConfig.digest)
            && Objects.equals(mediaType, manifestConfig.mediaType)
            && Objects.equals(size, manifestConfig.size);
    }

    @Override
    public int hashCode() {
        return Objects.hash(digest, mediaType, size);
    }

    @Override
    public String toString() {
        return "ManifestConfig("
            + "digest: " + getDigest() + ", "
            + "mediaType: " + getMediaType() + ", "
            + "size: " + getSize()
            + ")";
    }

}