/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.wave.api.v1.model.ManifestConfig;
import io.seqera.wave.api.v1.model.ManifestLayer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Manifest details of a container.
 */
@Serdeable
@JsonPropertyOrder({
    Manifest.JSON_PROPERTY_CONFIG,
    Manifest.JSON_PROPERTY_LAYERS,
    Manifest.JSON_PROPERTY_MEDIA_TYPE,
    Manifest.JSON_PROPERTY_SCHEMA_VERSION,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class Manifest {

    public static final String JSON_PROPERTY_CONFIG = "config";
    public static final String JSON_PROPERTY_LAYERS = "layers";
    public static final String JSON_PROPERTY_MEDIA_TYPE = "mediaType";
    public static final String JSON_PROPERTY_SCHEMA_VERSION = "schemaVersion";

    @NotNull
    @Valid
    @JsonProperty(JSON_PROPERTY_CONFIG)
    private ManifestConfig config;

    @NotNull
    @JsonProperty(JSON_PROPERTY_LAYERS)
    private List<@Valid ManifestLayer> layers = new ArrayList<>();

    @NotNull
    @JsonProperty(JSON_PROPERTY_MEDIA_TYPE)
    private String mediaType;

    @NotNull
    @JsonProperty(JSON_PROPERTY_SCHEMA_VERSION)
    private Integer schemaVersion;

    /**
     * @return the config property value
     */
    public ManifestConfig getConfig() {
        return config;
    }

    /**
     * Set the config property value
     *
     * @param config property value to set
     */
    public void setConfig(ManifestConfig config) {
        this.config = config;
    }

    /**
     * Set config in a chainable fashion.
     *
     * @return The same instance of Manifest for chaining.
     */
    public Manifest config(ManifestConfig config) {
        this.config = config;
        return this;
    }

    /**
     * @return the layers property value
     */
    public List<@Valid ManifestLayer> getLayers() {
        return layers;
    }

    /**
     * Set the layers property value
     *
     * @param layers property value to set
     */
    public void setLayers(List<@Valid ManifestLayer> layers) {
        this.layers = layers;
    }

    /**
     * Set layers in a chainable fashion.
     *
     * @return The same instance of Manifest for chaining.
     */
    public Manifest layers(List<@Valid ManifestLayer> layers) {
        this.layers = layers;
        return this;
    }
    /**
     * Add an item to the layers property in a chainable fashion.
     *
     * @return The same instance of Manifest for chaining.
     */
    public Manifest addLayersItem(ManifestLayer layersItem) {
        layers.add(layersItem);
        return this;
    }

    /**
     * @return the mediaType property value
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * Set the mediaType property value
     *
     * @param mediaType property value to set
     */
    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * Set mediaType in a chainable fashion.
     *
     * @return The same instance of Manifest for chaining.
     */
    public Manifest mediaType(String mediaType) {
        this.mediaType = mediaType;
        return this;
    }

    /**
     * @return the schemaVersion property value
     */
    public Integer getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Set the schemaVersion property value
     *
     * @param schemaVersion property value to set
     */
    public void setSchemaVersion(Integer schemaVersion) {
        this.schemaVersion = schemaVersion;
    }

    /**
     * Set schemaVersion in a chainable fashion.
     *
     * @return The same instance of Manifest for chaining.
     */
    public Manifest schemaVersion(Integer schemaVersion) {
        this.schemaVersion = schemaVersion;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var manifest = (Manifest) o;
        return Objects.equals(config, manifest.config)
            && Objects.equals(layers, manifest.layers)
            && Objects.equals(mediaType, manifest.mediaType)
            && Objects.equals(schemaVersion, manifest.schemaVersion);
    }

    @Override
    public int hashCode() {
        return Objects.hash(config, layers, mediaType, schemaVersion);
    }

    @Override
    public String toString() {
        return "Manifest("
            + "config: " + getConfig() + ", "
            + "layers: " + getLayers() + ", "
            + "mediaType: " + getMediaType() + ", "
            + "schemaVersion: " + getSchemaVersion()
            + ")";
    }

}