/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Options for Pixi environments.
 */
@Serdeable
@JsonPropertyOrder({
    PixiOpts.JSON_PROPERTY_BASE_PACKAGES,
    PixiOpts.JSON_PROPERTY_COMMANDS,
    PixiOpts.JSON_PROPERTY_PIXI_IMAGE,
    PixiOpts.JSON_PROPERTY_BASE_IMAGE,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class PixiOpts {

    public static final String JSON_PROPERTY_BASE_PACKAGES = "basePackages";
    public static final String JSON_PROPERTY_COMMANDS = "commands";
    public static final String JSON_PROPERTY_PIXI_IMAGE = "pixiImage";
    public static final String JSON_PROPERTY_BASE_IMAGE = "baseImage";

    /**
     * Names of base packages.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_BASE_PACKAGES)
    private String basePackages;

    /**
     * Command to be included in the container.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_COMMANDS)
    private List<@NotNull String> commands = new ArrayList<>();

    /**
     * Name of the docker image used to build Pixi containers.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_PIXI_IMAGE)
    private String pixiImage;

    /**
     * Base image for the final stage of multi-stage builds.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_BASE_IMAGE)
    private String baseImage;

    /**
     * Names of base packages.
     *
     * @return the basePackages property value
     */
    public String getBasePackages() {
        return basePackages;
    }

    /**
     * Set the basePackages property value
     *
     * @param basePackages property value to set
     */
    public void setBasePackages(String basePackages) {
        this.basePackages = basePackages;
    }

    /**
     * Set basePackages in a chainable fashion.
     *
     * @return The same instance of PixiOpts for chaining.
     */
    public PixiOpts basePackages(String basePackages) {
        this.basePackages = basePackages;
        return this;
    }

    /**
     * Command to be included in the container.
     *
     * @return the commands property value
     */
    public List<@NotNull String> getCommands() {
        return commands;
    }

    /**
     * Set the commands property value
     *
     * @param commands property value to set
     */
    public void setCommands(List<@NotNull String> commands) {
        this.commands = commands;
    }

    /**
     * Set commands in a chainable fashion.
     *
     * @return The same instance of PixiOpts for chaining.
     */
    public PixiOpts commands(List<@NotNull String> commands) {
        this.commands = commands;
        return this;
    }
    /**
     * Add an item to the commands property in a chainable fashion.
     *
     * @return The same instance of PixiOpts for chaining.
     */
    public PixiOpts addCommandsItem(String commandsItem) {
        commands.add(commandsItem);
        return this;
    }

    /**
     * Name of the docker image used to build Pixi containers.
     *
     * @return the pixiImage property value
     */
    public String getPixiImage() {
        return pixiImage;
    }

    /**
     * Set the pixiImage property value
     *
     * @param pixiImage property value to set
     */
    public void setPixiImage(String pixiImage) {
        this.pixiImage = pixiImage;
    }

    /**
     * Set pixiImage in a chainable fashion.
     *
     * @return The same instance of PixiOpts for chaining.
     */
    public PixiOpts pixiImage(String pixiImage) {
        this.pixiImage = pixiImage;
        return this;
    }

    /**
     * Base image for the final stage of multi-stage builds.
     *
     * @return the baseImage property value
     */
    public String getBaseImage() {
        return baseImage;
    }

    /**
     * Set the baseImage property value
     *
     * @param baseImage property value to set
     */
    public void setBaseImage(String baseImage) {
        this.baseImage = baseImage;
    }

    /**
     * Set baseImage in a chainable fashion.
     *
     * @return The same instance of PixiOpts for chaining.
     */
    public PixiOpts baseImage(String baseImage) {
        this.baseImage = baseImage;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var pixiOpts = (PixiOpts) o;
        return Objects.equals(basePackages, pixiOpts.basePackages)
            && Objects.equals(commands, pixiOpts.commands)
            && Objects.equals(pixiImage, pixiOpts.pixiImage)
            && Objects.equals(baseImage, pixiOpts.baseImage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(basePackages, commands, pixiImage, baseImage);
    }

    @Override
    public String toString() {
        return "PixiOpts("
            + "basePackages: " + getBasePackages() + ", "
            + "commands: " + getCommands() + ", "
            + "pixiImage: " + getPixiImage() + ", "
            + "baseImage: " + getBaseImage()
            + ")";
    }

}