/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Details about the root filesystem of a container.
 */
@Serdeable
@JsonPropertyOrder({
    RootFS.JSON_PROPERTY_DIFF_IDS,
    RootFS.JSON_PROPERTY_TYPE,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class RootFS {

    public static final String JSON_PROPERTY_DIFF_IDS = "diff_ids";
    public static final String JSON_PROPERTY_TYPE = "type";

    @NotNull
    @JsonProperty(JSON_PROPERTY_DIFF_IDS)
    private List<@NotNull String> diffIds = new ArrayList<>();

    @NotNull
    @JsonProperty(JSON_PROPERTY_TYPE)
    private String type;

    /**
     * @return the diffIds property value
     */
    public List<@NotNull String> getDiffIds() {
        return diffIds;
    }

    /**
     * Set the diffIds property value
     *
     * @param diffIds property value to set
     */
    public void setDiffIds(List<@NotNull String> diffIds) {
        this.diffIds = diffIds;
    }

    /**
     * Set diffIds in a chainable fashion.
     *
     * @return The same instance of RootFS for chaining.
     */
    public RootFS diffIds(List<@NotNull String> diffIds) {
        this.diffIds = diffIds;
        return this;
    }
    /**
     * Add an item to the diffIds property in a chainable fashion.
     *
     * @return The same instance of RootFS for chaining.
     */
    public RootFS addDiffIdsItem(String diffIdsItem) {
        diffIds.add(diffIdsItem);
        return this;
    }

    /**
     * @return the type property value
     */
    public String getType() {
        return type;
    }

    /**
     * Set the type property value
     *
     * @param type property value to set
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Set type in a chainable fashion.
     *
     * @return The same instance of RootFS for chaining.
     */
    public RootFS type(String type) {
        this.type = type;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var rootFS = (RootFS) o;
        return Objects.equals(diffIds, rootFS.diffIds)
            && Objects.equals(type, rootFS.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(diffIds, type);
    }

    @Override
    public String toString() {
        return "RootFS("
            + "diffIds: " + getDiffIds() + ", "
            + "type: " + getType()
            + ")";
    }

}