/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Response payload for a scan submission.
 */
@Serdeable
@JsonPropertyOrder({
    ScanSubmitResponse.JSON_PROPERTY_SCAN_ID,
    ScanSubmitResponse.JSON_PROPERTY_TARGET_IMAGE,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ScanSubmitResponse {

    public static final String JSON_PROPERTY_SCAN_ID = "scanId";
    public static final String JSON_PROPERTY_TARGET_IMAGE = "targetImage";

    /**
     * Identifier of the submitted scan.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_SCAN_ID)
    private String scanId;

    /**
     * Target container image being scanned.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TARGET_IMAGE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String targetImage;

    /**
     * Identifier of the submitted scan.
     *
     * @return the scanId property value
     */
    public String getScanId() {
        return scanId;
    }

    /**
     * Set the scanId property value
     *
     * @param scanId property value to set
     */
    public void setScanId(String scanId) {
        this.scanId = scanId;
    }

    /**
     * Set scanId in a chainable fashion.
     *
     * @return The same instance of ScanSubmitResponse for chaining.
     */
    public ScanSubmitResponse scanId(String scanId) {
        this.scanId = scanId;
        return this;
    }

    /**
     * Target container image being scanned.
     *
     * @return the targetImage property value
     */
    public String getTargetImage() {
        return targetImage;
    }

    /**
     * Set the targetImage property value
     *
     * @param targetImage property value to set
     */
    public void setTargetImage(String targetImage) {
        this.targetImage = targetImage;
    }

    /**
     * Set targetImage in a chainable fashion.
     *
     * @return The same instance of ScanSubmitResponse for chaining.
     */
    public ScanSubmitResponse targetImage(String targetImage) {
        this.targetImage = targetImage;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var scanSubmitResponse = (ScanSubmitResponse) o;
        return Objects.equals(scanId, scanSubmitResponse.scanId)
            && Objects.equals(targetImage, scanSubmitResponse.targetImage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(scanId, targetImage);
    }

    @Override
    public String toString() {
        return "ScanSubmitResponse("
            + "scanId: " + getScanId() + ", "
            + "targetImage: " + getTargetImage()
            + ")";
    }

}