/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Request payload for submitting a container scan.
 */
@Serdeable
@JsonPropertyOrder({
    ScanSubmitRequest.JSON_PROPERTY_CONTAINER_IMAGE,
    ScanSubmitRequest.JSON_PROPERTY_MIRROR_ID,
    ScanSubmitRequest.JSON_PROPERTY_BUILD_ID,
    ScanSubmitRequest.JSON_PROPERTY_CONTAINER_PLATFORM,
    ScanSubmitRequest.JSON_PROPERTY_TOWER_ACCESS_TOKEN,
    ScanSubmitRequest.JSON_PROPERTY_TOWER_ENDPOINT,
    ScanSubmitRequest.JSON_PROPERTY_TOWER_WORKSPACE_ID,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ScanSubmitRequest {

    public static final String JSON_PROPERTY_CONTAINER_IMAGE = "containerImage";
    public static final String JSON_PROPERTY_MIRROR_ID = "mirrorId";
    public static final String JSON_PROPERTY_BUILD_ID = "buildId";
    public static final String JSON_PROPERTY_CONTAINER_PLATFORM = "containerPlatform";
    public static final String JSON_PROPERTY_TOWER_ACCESS_TOKEN = "towerAccessToken";
    public static final String JSON_PROPERTY_TOWER_ENDPOINT = "towerEndpoint";
    public static final String JSON_PROPERTY_TOWER_WORKSPACE_ID = "towerWorkspaceId";

    /**
     * Container image to scan, e.g. &#x60;docker.io/library/ubuntu:latest&#x60;. Mutually exclusive with mirrorId and buildId.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_CONTAINER_IMAGE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String containerImage;

    /**
     * Existing mirror id to scan. Mutually exclusive with containerImage and buildId.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_MIRROR_ID)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String mirrorId;

    /**
     * Existing build id to scan. Mutually exclusive with containerImage and mirrorId.
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_BUILD_ID)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String buildId;

    /**
     * Target platform of the image (optional, e.g. &#x60;linux/amd64&#x60;).
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_CONTAINER_PLATFORM)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String containerPlatform;

    /**
     * Seqera Platform access token granting registry access (optional).
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TOWER_ACCESS_TOKEN)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String towerAccessToken;

    /**
     * Seqera Platform endpoint (optional).
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TOWER_ENDPOINT)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String towerEndpoint;

    /**
     * Seqera Platform workspace id (optional).
     */
    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TOWER_WORKSPACE_ID)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Long towerWorkspaceId;

    /**
     * Container image to scan, e.g. &#x60;docker.io/library/ubuntu:latest&#x60;. Mutually exclusive with mirrorId and buildId.
     *
     * @return the containerImage property value
     */
    public String getContainerImage() {
        return containerImage;
    }

    /**
     * Set the containerImage property value
     *
     * @param containerImage property value to set
     */
    public void setContainerImage(String containerImage) {
        this.containerImage = containerImage;
    }

    /**
     * Set containerImage in a chainable fashion.
     *
     * @return The same instance of ScanSubmitRequest for chaining.
     */
    public ScanSubmitRequest containerImage(String containerImage) {
        this.containerImage = containerImage;
        return this;
    }

    /**
     * Existing mirror id to scan. Mutually exclusive with containerImage and buildId.
     *
     * @return the mirrorId property value
     */
    public String getMirrorId() {
        return mirrorId;
    }

    /**
     * Set the mirrorId property value
     *
     * @param mirrorId property value to set
     */
    public void setMirrorId(String mirrorId) {
        this.mirrorId = mirrorId;
    }

    /**
     * Set mirrorId in a chainable fashion.
     *
     * @return The same instance of ScanSubmitRequest for chaining.
     */
    public ScanSubmitRequest mirrorId(String mirrorId) {
        this.mirrorId = mirrorId;
        return this;
    }

    /**
     * Existing build id to scan. Mutually exclusive with containerImage and mirrorId.
     *
     * @return the buildId property value
     */
    public String getBuildId() {
        return buildId;
    }

    /**
     * Set the buildId property value
     *
     * @param buildId property value to set
     */
    public void setBuildId(String buildId) {
        this.buildId = buildId;
    }

    /**
     * Set buildId in a chainable fashion.
     *
     * @return The same instance of ScanSubmitRequest for chaining.
     */
    public ScanSubmitRequest buildId(String buildId) {
        this.buildId = buildId;
        return this;
    }

    /**
     * Target platform of the image (optional, e.g. &#x60;linux/amd64&#x60;).
     *
     * @return the containerPlatform property value
     */
    public String getContainerPlatform() {
        return containerPlatform;
    }

    /**
     * Set the containerPlatform property value
     *
     * @param containerPlatform property value to set
     */
    public void setContainerPlatform(String containerPlatform) {
        this.containerPlatform = containerPlatform;
    }

    /**
     * Set containerPlatform in a chainable fashion.
     *
     * @return The same instance of ScanSubmitRequest for chaining.
     */
    public ScanSubmitRequest containerPlatform(String containerPlatform) {
        this.containerPlatform = containerPlatform;
        return this;
    }

    /**
     * Seqera Platform access token granting registry access (optional).
     *
     * @return the towerAccessToken property value
     */
    public String getTowerAccessToken() {
        return towerAccessToken;
    }

    /**
     * Set the towerAccessToken property value
     *
     * @param towerAccessToken property value to set
     */
    public void setTowerAccessToken(String towerAccessToken) {
        this.towerAccessToken = towerAccessToken;
    }

    /**
     * Set towerAccessToken in a chainable fashion.
     *
     * @return The same instance of ScanSubmitRequest for chaining.
     */
    public ScanSubmitRequest towerAccessToken(String towerAccessToken) {
        this.towerAccessToken = towerAccessToken;
        return this;
    }

    /**
     * Seqera Platform endpoint (optional).
     *
     * @return the towerEndpoint property value
     */
    public String getTowerEndpoint() {
        return towerEndpoint;
    }

    /**
     * Set the towerEndpoint property value
     *
     * @param towerEndpoint property value to set
     */
    public void setTowerEndpoint(String towerEndpoint) {
        this.towerEndpoint = towerEndpoint;
    }

    /**
     * Set towerEndpoint in a chainable fashion.
     *
     * @return The same instance of ScanSubmitRequest for chaining.
     */
    public ScanSubmitRequest towerEndpoint(String towerEndpoint) {
        this.towerEndpoint = towerEndpoint;
        return this;
    }

    /**
     * Seqera Platform workspace id (optional).
     *
     * @return the towerWorkspaceId property value
     */
    public Long getTowerWorkspaceId() {
        return towerWorkspaceId;
    }

    /**
     * Set the towerWorkspaceId property value
     *
     * @param towerWorkspaceId property value to set
     */
    public void setTowerWorkspaceId(Long towerWorkspaceId) {
        this.towerWorkspaceId = towerWorkspaceId;
    }

    /**
     * Set towerWorkspaceId in a chainable fashion.
     *
     * @return The same instance of ScanSubmitRequest for chaining.
     */
    public ScanSubmitRequest towerWorkspaceId(Long towerWorkspaceId) {
        this.towerWorkspaceId = towerWorkspaceId;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var scanSubmitRequest = (ScanSubmitRequest) o;
        return Objects.equals(containerImage, scanSubmitRequest.containerImage)
            && Objects.equals(mirrorId, scanSubmitRequest.mirrorId)
            && Objects.equals(buildId, scanSubmitRequest.buildId)
            && Objects.equals(containerPlatform, scanSubmitRequest.containerPlatform)
            && Objects.equals(towerAccessToken, scanSubmitRequest.towerAccessToken)
            && Objects.equals(towerEndpoint, scanSubmitRequest.towerEndpoint)
            && Objects.equals(towerWorkspaceId, scanSubmitRequest.towerWorkspaceId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(containerImage, mirrorId, buildId, containerPlatform, towerAccessToken, towerEndpoint, towerWorkspaceId);
    }

    @Override
    public String toString() {
        return "ScanSubmitRequest("
            + "containerImage: " + getContainerImage() + ", "
            + "mirrorId: " + getMirrorId() + ", "
            + "buildId: " + getBuildId() + ", "
            + "containerPlatform: " + getContainerPlatform() + ", "
            + "towerAccessToken: " + getTowerAccessToken() + ", "
            + "towerEndpoint: " + getTowerEndpoint() + ", "
            + "towerWorkspaceId: " + getTowerWorkspaceId()
            + ")";
    }

}