/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Wave service information.
 */
@Serdeable
@JsonPropertyOrder({
    ServiceInfo.JSON_PROPERTY_VERSION,
    ServiceInfo.JSON_PROPERTY_COMMIT_ID,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ServiceInfo {

    public static final String JSON_PROPERTY_VERSION = "version";
    public static final String JSON_PROPERTY_COMMIT_ID = "commitId";

    /**
     * Application version, e.g. &#x60;1.33.5&#x60;.
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_VERSION)
    private String version;

    /**
     * Build commit id (short SHA).
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_COMMIT_ID)
    private String commitId;

    /**
     * Application version, e.g. &#x60;1.33.5&#x60;.
     *
     * @return the version property value
     */
    public String getVersion() {
        return version;
    }

    /**
     * Set the version property value
     *
     * @param version property value to set
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * Set version in a chainable fashion.
     *
     * @return The same instance of ServiceInfo for chaining.
     */
    public ServiceInfo version(String version) {
        this.version = version;
        return this;
    }

    /**
     * Build commit id (short SHA).
     *
     * @return the commitId property value
     */
    public String getCommitId() {
        return commitId;
    }

    /**
     * Set the commitId property value
     *
     * @param commitId property value to set
     */
    public void setCommitId(String commitId) {
        this.commitId = commitId;
    }

    /**
     * Set commitId in a chainable fashion.
     *
     * @return The same instance of ServiceInfo for chaining.
     */
    public ServiceInfo commitId(String commitId) {
        this.commitId = commitId;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var serviceInfo = (ServiceInfo) o;
        return Objects.equals(version, serviceInfo.version)
            && Objects.equals(commitId, serviceInfo.commitId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(version, commitId);
    }

    @Override
    public String toString() {
        return "ServiceInfo("
            + "version: " + getVersion() + ", "
            + "commitId: " + getCommitId()
            + ")";
    }

}