/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Wave USer details
 */
@Serdeable
@JsonPropertyOrder({
    User.JSON_PROPERTY_ID,
    User.JSON_PROPERTY_USER_NAME,
    User.JSON_PROPERTY_EMAIL,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class User {

    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_USER_NAME = "userName";
    public static final String JSON_PROPERTY_EMAIL = "email";

    @NotNull
    @JsonProperty(JSON_PROPERTY_ID)
    private Long id;

    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_NAME)
    private String userName;

    @NotNull
    @JsonProperty(JSON_PROPERTY_EMAIL)
    private String email;

    /**
     * @return the id property value
     */
    public Long getId() {
        return id;
    }

    /**
     * Set the id property value
     *
     * @param id property value to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Set id in a chainable fashion.
     *
     * @return The same instance of User for chaining.
     */
    public User id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * @return the userName property value
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Set the userName property value
     *
     * @param userName property value to set
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Set userName in a chainable fashion.
     *
     * @return The same instance of User for chaining.
     */
    public User userName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * @return the email property value
     */
    public String getEmail() {
        return email;
    }

    /**
     * Set the email property value
     *
     * @param email property value to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Set email in a chainable fashion.
     *
     * @return The same instance of User for chaining.
     */
    public User email(String email) {
        this.email = email;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var user = (User) o;
        return Objects.equals(id, user.id)
            && Objects.equals(userName, user.userName)
            && Objects.equals(email, user.email);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, userName, email);
    }

    @Override
    public String toString() {
        return "User("
            + "id: " + getId() + ", "
            + "userName: " + getUserName() + ", "
            + "email: " + getEmail()
            + ")";
    }

}