/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * request payload of validate credentials request
 */
@Serdeable
@JsonPropertyOrder({
    ValidateRegistryCredsRequest.JSON_PROPERTY_PASSWORD,
    ValidateRegistryCredsRequest.JSON_PROPERTY_REGISTRY,
    ValidateRegistryCredsRequest.JSON_PROPERTY_USER_NAME,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class ValidateRegistryCredsRequest {

    public static final String JSON_PROPERTY_PASSWORD = "password";
    public static final String JSON_PROPERTY_REGISTRY = "registry";
    public static final String JSON_PROPERTY_USER_NAME = "userName";

    @NotNull
    @JsonProperty(JSON_PROPERTY_PASSWORD)
    private String password;

    @NotNull
    @JsonProperty(JSON_PROPERTY_REGISTRY)
    private String registry;

    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_NAME)
    private String userName;

    /**
     * @return the password property value
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the password property value
     *
     * @param password property value to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Set password in a chainable fashion.
     *
     * @return The same instance of ValidateRegistryCredsRequest for chaining.
     */
    public ValidateRegistryCredsRequest password(String password) {
        this.password = password;
        return this;
    }

    /**
     * @return the registry property value
     */
    public String getRegistry() {
        return registry;
    }

    /**
     * Set the registry property value
     *
     * @param registry property value to set
     */
    public void setRegistry(String registry) {
        this.registry = registry;
    }

    /**
     * Set registry in a chainable fashion.
     *
     * @return The same instance of ValidateRegistryCredsRequest for chaining.
     */
    public ValidateRegistryCredsRequest registry(String registry) {
        this.registry = registry;
        return this;
    }

    /**
     * @return the userName property value
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Set the userName property value
     *
     * @param userName property value to set
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Set userName in a chainable fashion.
     *
     * @return The same instance of ValidateRegistryCredsRequest for chaining.
     */
    public ValidateRegistryCredsRequest userName(String userName) {
        this.userName = userName;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var validateRegistryCredsRequest = (ValidateRegistryCredsRequest) o;
        return Objects.equals(password, validateRegistryCredsRequest.password)
            && Objects.equals(registry, validateRegistryCredsRequest.registry)
            && Objects.equals(userName, validateRegistryCredsRequest.userName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(password, registry, userName);
    }

    @Override
    public String toString() {
        return "ValidateRegistryCredsRequest("
            + "password: " + getPassword() + ", "
            + "registry: " + getRegistry() + ", "
            + "userName: " + getUserName()
            + ")";
    }

}