/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.wave.api.v1.model.ContainerConfig;
import io.seqera.wave.api.v1.model.User;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Wave container details
 */
@Serdeable
@JsonPropertyOrder({
    WaveContainerRecord.JSON_PROPERTY_USER,
    WaveContainerRecord.JSON_PROPERTY_WORKSPACE_ID,
    WaveContainerRecord.JSON_PROPERTY_CONTAINER_CONFIG,
    WaveContainerRecord.JSON_PROPERTY_TIMESTAMP,
    WaveContainerRecord.JSON_PROPERTY_EXPIRATION,
    WaveContainerRecord.JSON_PROPERTY_CONTAINER_IMAGE,
    WaveContainerRecord.JSON_PROPERTY_CONTAINER_FILE,
    WaveContainerRecord.JSON_PROPERTY_CONDA_FILE,
    WaveContainerRecord.JSON_PROPERTY_PLATFORM,
    WaveContainerRecord.JSON_PROPERTY_TOWER_ENDPOINT,
    WaveContainerRecord.JSON_PROPERTY_BUILD_REPOSITORY,
    WaveContainerRecord.JSON_PROPERTY_CACHE_REPOSITORY,
    WaveContainerRecord.JSON_PROPERTY_FINGERPRINT,
    WaveContainerRecord.JSON_PROPERTY_ZONE_ID,
    WaveContainerRecord.JSON_PROPERTY_IP_ADDRESS,
    WaveContainerRecord.JSON_PROPERTY_SOURCE_IMAGE,
    WaveContainerRecord.JSON_PROPERTY_SOURCE_DIGEST,
    WaveContainerRecord.JSON_PROPERTY_WAVE_IMAGE,
    WaveContainerRecord.JSON_PROPERTY_WAVE_DIGEST,
    WaveContainerRecord.JSON_PROPERTY_BUILD_ID,
    WaveContainerRecord.JSON_PROPERTY_BUILD_NEW,
    WaveContainerRecord.JSON_PROPERTY_FREEZE,
    WaveContainerRecord.JSON_PROPERTY_FUSION_VERSION,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class WaveContainerRecord {

    public static final String JSON_PROPERTY_USER = "user";
    public static final String JSON_PROPERTY_WORKSPACE_ID = "workspaceId";
    public static final String JSON_PROPERTY_CONTAINER_CONFIG = "containerConfig";
    public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
    public static final String JSON_PROPERTY_EXPIRATION = "expiration";
    public static final String JSON_PROPERTY_CONTAINER_IMAGE = "containerImage";
    public static final String JSON_PROPERTY_CONTAINER_FILE = "containerFile";
    public static final String JSON_PROPERTY_CONDA_FILE = "condaFile";
    public static final String JSON_PROPERTY_PLATFORM = "platform";
    public static final String JSON_PROPERTY_TOWER_ENDPOINT = "towerEndpoint";
    public static final String JSON_PROPERTY_BUILD_REPOSITORY = "buildRepository";
    public static final String JSON_PROPERTY_CACHE_REPOSITORY = "cacheRepository";
    public static final String JSON_PROPERTY_FINGERPRINT = "fingerprint";
    public static final String JSON_PROPERTY_ZONE_ID = "zoneId";
    public static final String JSON_PROPERTY_IP_ADDRESS = "ipAddress";
    public static final String JSON_PROPERTY_SOURCE_IMAGE = "sourceImage";
    public static final String JSON_PROPERTY_SOURCE_DIGEST = "sourceDigest";
    public static final String JSON_PROPERTY_WAVE_IMAGE = "waveImage";
    public static final String JSON_PROPERTY_WAVE_DIGEST = "waveDigest";
    public static final String JSON_PROPERTY_BUILD_ID = "buildId";
    public static final String JSON_PROPERTY_BUILD_NEW = "buildNew";
    public static final String JSON_PROPERTY_FREEZE = "freeze";
    public static final String JSON_PROPERTY_FUSION_VERSION = "fusionVersion";

    @NotNull
    @Valid
    @JsonProperty(JSON_PROPERTY_USER)
    private User user;

    @NotNull
    @JsonProperty(JSON_PROPERTY_WORKSPACE_ID)
    private Long workspaceId;

    @NotNull
    @Valid
    @JsonProperty(JSON_PROPERTY_CONTAINER_CONFIG)
    private ContainerConfig containerConfig;

    @NotNull
    @JsonProperty(JSON_PROPERTY_TIMESTAMP)
    private String timestamp;

    @NotNull
    @JsonProperty(JSON_PROPERTY_EXPIRATION)
    private String expiration;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_CONTAINER_IMAGE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String containerImage;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_CONTAINER_FILE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String containerFile;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_CONDA_FILE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String condaFile;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_PLATFORM)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String platform;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_TOWER_ENDPOINT)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String towerEndpoint;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_BUILD_REPOSITORY)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String buildRepository;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_CACHE_REPOSITORY)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String cacheRepository;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_FINGERPRINT)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String fingerprint;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_ZONE_ID)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String zoneId;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_IP_ADDRESS)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String ipAddress;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_SOURCE_IMAGE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String sourceImage;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_SOURCE_DIGEST)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String sourceDigest;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_WAVE_IMAGE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String waveImage;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_WAVE_DIGEST)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String waveDigest;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_BUILD_ID)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String buildId;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_BUILD_NEW)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Boolean buildNew;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_FREEZE)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private Boolean freeze;

    @Nullable(inherited = true)
    @JsonProperty(JSON_PROPERTY_FUSION_VERSION)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String fusionVersion;

    /**
     * @return the user property value
     */
    public User getUser() {
        return user;
    }

    /**
     * Set the user property value
     *
     * @param user property value to set
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Set user in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord user(User user) {
        this.user = user;
        return this;
    }

    /**
     * @return the workspaceId property value
     */
    public Long getWorkspaceId() {
        return workspaceId;
    }

    /**
     * Set the workspaceId property value
     *
     * @param workspaceId property value to set
     */
    public void setWorkspaceId(Long workspaceId) {
        this.workspaceId = workspaceId;
    }

    /**
     * Set workspaceId in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord workspaceId(Long workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }

    /**
     * @return the containerConfig property value
     */
    public ContainerConfig getContainerConfig() {
        return containerConfig;
    }

    /**
     * Set the containerConfig property value
     *
     * @param containerConfig property value to set
     */
    public void setContainerConfig(ContainerConfig containerConfig) {
        this.containerConfig = containerConfig;
    }

    /**
     * Set containerConfig in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord containerConfig(ContainerConfig containerConfig) {
        this.containerConfig = containerConfig;
        return this;
    }

    /**
     * @return the timestamp property value
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Set the timestamp property value
     *
     * @param timestamp property value to set
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Set timestamp in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord timestamp(String timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    /**
     * @return the expiration property value
     */
    public String getExpiration() {
        return expiration;
    }

    /**
     * Set the expiration property value
     *
     * @param expiration property value to set
     */
    public void setExpiration(String expiration) {
        this.expiration = expiration;
    }

    /**
     * Set expiration in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord expiration(String expiration) {
        this.expiration = expiration;
        return this;
    }

    /**
     * @return the containerImage property value
     */
    public String getContainerImage() {
        return containerImage;
    }

    /**
     * Set the containerImage property value
     *
     * @param containerImage property value to set
     */
    public void setContainerImage(String containerImage) {
        this.containerImage = containerImage;
    }

    /**
     * Set containerImage in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord containerImage(String containerImage) {
        this.containerImage = containerImage;
        return this;
    }

    /**
     * @return the containerFile property value
     */
    public String getContainerFile() {
        return containerFile;
    }

    /**
     * Set the containerFile property value
     *
     * @param containerFile property value to set
     */
    public void setContainerFile(String containerFile) {
        this.containerFile = containerFile;
    }

    /**
     * Set containerFile in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord containerFile(String containerFile) {
        this.containerFile = containerFile;
        return this;
    }

    /**
     * @return the condaFile property value
     */
    public String getCondaFile() {
        return condaFile;
    }

    /**
     * Set the condaFile property value
     *
     * @param condaFile property value to set
     */
    public void setCondaFile(String condaFile) {
        this.condaFile = condaFile;
    }

    /**
     * Set condaFile in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord condaFile(String condaFile) {
        this.condaFile = condaFile;
        return this;
    }

    /**
     * @return the platform property value
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Set the platform property value
     *
     * @param platform property value to set
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * Set platform in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord platform(String platform) {
        this.platform = platform;
        return this;
    }

    /**
     * @return the towerEndpoint property value
     */
    public String getTowerEndpoint() {
        return towerEndpoint;
    }

    /**
     * Set the towerEndpoint property value
     *
     * @param towerEndpoint property value to set
     */
    public void setTowerEndpoint(String towerEndpoint) {
        this.towerEndpoint = towerEndpoint;
    }

    /**
     * Set towerEndpoint in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord towerEndpoint(String towerEndpoint) {
        this.towerEndpoint = towerEndpoint;
        return this;
    }

    /**
     * @return the buildRepository property value
     */
    public String getBuildRepository() {
        return buildRepository;
    }

    /**
     * Set the buildRepository property value
     *
     * @param buildRepository property value to set
     */
    public void setBuildRepository(String buildRepository) {
        this.buildRepository = buildRepository;
    }

    /**
     * Set buildRepository in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord buildRepository(String buildRepository) {
        this.buildRepository = buildRepository;
        return this;
    }

    /**
     * @return the cacheRepository property value
     */
    public String getCacheRepository() {
        return cacheRepository;
    }

    /**
     * Set the cacheRepository property value
     *
     * @param cacheRepository property value to set
     */
    public void setCacheRepository(String cacheRepository) {
        this.cacheRepository = cacheRepository;
    }

    /**
     * Set cacheRepository in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord cacheRepository(String cacheRepository) {
        this.cacheRepository = cacheRepository;
        return this;
    }

    /**
     * @return the fingerprint property value
     */
    public String getFingerprint() {
        return fingerprint;
    }

    /**
     * Set the fingerprint property value
     *
     * @param fingerprint property value to set
     */
    public void setFingerprint(String fingerprint) {
        this.fingerprint = fingerprint;
    }

    /**
     * Set fingerprint in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord fingerprint(String fingerprint) {
        this.fingerprint = fingerprint;
        return this;
    }

    /**
     * @return the zoneId property value
     */
    public String getZoneId() {
        return zoneId;
    }

    /**
     * Set the zoneId property value
     *
     * @param zoneId property value to set
     */
    public void setZoneId(String zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * Set zoneId in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord zoneId(String zoneId) {
        this.zoneId = zoneId;
        return this;
    }

    /**
     * @return the ipAddress property value
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Set the ipAddress property value
     *
     * @param ipAddress property value to set
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * Set ipAddress in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord ipAddress(String ipAddress) {
        this.ipAddress = ipAddress;
        return this;
    }

    /**
     * @return the sourceImage property value
     */
    public String getSourceImage() {
        return sourceImage;
    }

    /**
     * Set the sourceImage property value
     *
     * @param sourceImage property value to set
     */
    public void setSourceImage(String sourceImage) {
        this.sourceImage = sourceImage;
    }

    /**
     * Set sourceImage in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord sourceImage(String sourceImage) {
        this.sourceImage = sourceImage;
        return this;
    }

    /**
     * @return the sourceDigest property value
     */
    public String getSourceDigest() {
        return sourceDigest;
    }

    /**
     * Set the sourceDigest property value
     *
     * @param sourceDigest property value to set
     */
    public void setSourceDigest(String sourceDigest) {
        this.sourceDigest = sourceDigest;
    }

    /**
     * Set sourceDigest in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord sourceDigest(String sourceDigest) {
        this.sourceDigest = sourceDigest;
        return this;
    }

    /**
     * @return the waveImage property value
     */
    public String getWaveImage() {
        return waveImage;
    }

    /**
     * Set the waveImage property value
     *
     * @param waveImage property value to set
     */
    public void setWaveImage(String waveImage) {
        this.waveImage = waveImage;
    }

    /**
     * Set waveImage in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord waveImage(String waveImage) {
        this.waveImage = waveImage;
        return this;
    }

    /**
     * @return the waveDigest property value
     */
    public String getWaveDigest() {
        return waveDigest;
    }

    /**
     * Set the waveDigest property value
     *
     * @param waveDigest property value to set
     */
    public void setWaveDigest(String waveDigest) {
        this.waveDigest = waveDigest;
    }

    /**
     * Set waveDigest in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord waveDigest(String waveDigest) {
        this.waveDigest = waveDigest;
        return this;
    }

    /**
     * @return the buildId property value
     */
    public String getBuildId() {
        return buildId;
    }

    /**
     * Set the buildId property value
     *
     * @param buildId property value to set
     */
    public void setBuildId(String buildId) {
        this.buildId = buildId;
    }

    /**
     * Set buildId in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord buildId(String buildId) {
        this.buildId = buildId;
        return this;
    }

    /**
     * @return the buildNew property value
     */
    public Boolean getBuildNew() {
        return buildNew;
    }

    /**
     * Set the buildNew property value
     *
     * @param buildNew property value to set
     */
    public void setBuildNew(Boolean buildNew) {
        this.buildNew = buildNew;
    }

    /**
     * Set buildNew in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord buildNew(Boolean buildNew) {
        this.buildNew = buildNew;
        return this;
    }

    /**
     * @return the freeze property value
     */
    public Boolean getFreeze() {
        return freeze;
    }

    /**
     * Set the freeze property value
     *
     * @param freeze property value to set
     */
    public void setFreeze(Boolean freeze) {
        this.freeze = freeze;
    }

    /**
     * Set freeze in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord freeze(Boolean freeze) {
        this.freeze = freeze;
        return this;
    }

    /**
     * @return the fusionVersion property value
     */
    public String getFusionVersion() {
        return fusionVersion;
    }

    /**
     * Set the fusionVersion property value
     *
     * @param fusionVersion property value to set
     */
    public void setFusionVersion(String fusionVersion) {
        this.fusionVersion = fusionVersion;
    }

    /**
     * Set fusionVersion in a chainable fashion.
     *
     * @return The same instance of WaveContainerRecord for chaining.
     */
    public WaveContainerRecord fusionVersion(String fusionVersion) {
        this.fusionVersion = fusionVersion;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var waveContainerRecord = (WaveContainerRecord) o;
        return Objects.equals(user, waveContainerRecord.user)
            && Objects.equals(workspaceId, waveContainerRecord.workspaceId)
            && Objects.equals(containerConfig, waveContainerRecord.containerConfig)
            && Objects.equals(timestamp, waveContainerRecord.timestamp)
            && Objects.equals(expiration, waveContainerRecord.expiration)
            && Objects.equals(containerImage, waveContainerRecord.containerImage)
            && Objects.equals(containerFile, waveContainerRecord.containerFile)
            && Objects.equals(condaFile, waveContainerRecord.condaFile)
            && Objects.equals(platform, waveContainerRecord.platform)
            && Objects.equals(towerEndpoint, waveContainerRecord.towerEndpoint)
            && Objects.equals(buildRepository, waveContainerRecord.buildRepository)
            && Objects.equals(cacheRepository, waveContainerRecord.cacheRepository)
            && Objects.equals(fingerprint, waveContainerRecord.fingerprint)
            && Objects.equals(zoneId, waveContainerRecord.zoneId)
            && Objects.equals(ipAddress, waveContainerRecord.ipAddress)
            && Objects.equals(sourceImage, waveContainerRecord.sourceImage)
            && Objects.equals(sourceDigest, waveContainerRecord.sourceDigest)
            && Objects.equals(waveImage, waveContainerRecord.waveImage)
            && Objects.equals(waveDigest, waveContainerRecord.waveDigest)
            && Objects.equals(buildId, waveContainerRecord.buildId)
            && Objects.equals(buildNew, waveContainerRecord.buildNew)
            && Objects.equals(freeze, waveContainerRecord.freeze)
            && Objects.equals(fusionVersion, waveContainerRecord.fusionVersion);
    }

    @Override
    public int hashCode() {
        return Objects.hash(user, workspaceId, containerConfig, timestamp, expiration, containerImage, containerFile, condaFile, platform, towerEndpoint, buildRepository, cacheRepository, fingerprint, zoneId, ipAddress, sourceImage, sourceDigest, waveImage, waveDigest, buildId, buildNew, freeze, fusionVersion);
    }

    @Override
    public String toString() {
        return "WaveContainerRecord("
            + "user: " + getUser() + ", "
            + "workspaceId: " + getWorkspaceId() + ", "
            + "containerConfig: " + getContainerConfig() + ", "
            + "timestamp: " + getTimestamp() + ", "
            + "expiration: " + getExpiration() + ", "
            + "containerImage: " + getContainerImage() + ", "
            + "containerFile: " + getContainerFile() + ", "
            + "condaFile: " + getCondaFile() + ", "
            + "platform: " + getPlatform() + ", "
            + "towerEndpoint: " + getTowerEndpoint() + ", "
            + "buildRepository: " + getBuildRepository() + ", "
            + "cacheRepository: " + getCacheRepository() + ", "
            + "fingerprint: " + getFingerprint() + ", "
            + "zoneId: " + getZoneId() + ", "
            + "ipAddress: " + getIpAddress() + ", "
            + "sourceImage: " + getSourceImage() + ", "
            + "sourceDigest: " + getSourceDigest() + ", "
            + "waveImage: " + getWaveImage() + ", "
            + "waveDigest: " + getWaveDigest() + ", "
            + "buildId: " + getBuildId() + ", "
            + "buildNew: " + getBuildNew() + ", "
            + "freeze: " + getFreeze() + ", "
            + "fusionVersion: " + getFusionVersion()
            + ")";
    }

}