/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.wave.api.v1.model.Vulnerability;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Response Payload for wave scan
 */
@Serdeable
@JsonPropertyOrder({
    WaveScanRecord.JSON_PROPERTY_BUILD_ID,
    WaveScanRecord.JSON_PROPERTY_DURATION,
    WaveScanRecord.JSON_PROPERTY_CONTAINER_IMAGE,
    WaveScanRecord.JSON_PROPERTY_ID,
    WaveScanRecord.JSON_PROPERTY_START_TIME,
    WaveScanRecord.JSON_PROPERTY_STATUS,
    WaveScanRecord.JSON_PROPERTY_VULNERABILITIES,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class WaveScanRecord {

    public static final String JSON_PROPERTY_BUILD_ID = "buildId";
    public static final String JSON_PROPERTY_DURATION = "duration";
    public static final String JSON_PROPERTY_CONTAINER_IMAGE = "containerImage";
    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_START_TIME = "startTime";
    public static final String JSON_PROPERTY_STATUS = "status";
    public static final String JSON_PROPERTY_VULNERABILITIES = "vulnerabilities";

    @NotNull
    @JsonProperty(JSON_PROPERTY_BUILD_ID)
    private String buildId;

    @NotNull
    @JsonProperty(JSON_PROPERTY_DURATION)
    private Long duration;

    @NotNull
    @JsonProperty(JSON_PROPERTY_CONTAINER_IMAGE)
    private String containerImage;

    @NotNull
    @JsonProperty(JSON_PROPERTY_ID)
    private String id;

    @NotNull
    @JsonProperty(JSON_PROPERTY_START_TIME)
    private String startTime;

    @NotNull
    @JsonProperty(JSON_PROPERTY_STATUS)
    private String status;

    @NotNull
    @JsonProperty(JSON_PROPERTY_VULNERABILITIES)
    private List<@Valid Vulnerability> vulnerabilities = new ArrayList<>();

    /**
     * @return the buildId property value
     */
    public String getBuildId() {
        return buildId;
    }

    /**
     * Set the buildId property value
     *
     * @param buildId property value to set
     */
    public void setBuildId(String buildId) {
        this.buildId = buildId;
    }

    /**
     * Set buildId in a chainable fashion.
     *
     * @return The same instance of WaveScanRecord for chaining.
     */
    public WaveScanRecord buildId(String buildId) {
        this.buildId = buildId;
        return this;
    }

    /**
     * @return the duration property value
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * Set the duration property value
     *
     * @param duration property value to set
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * Set duration in a chainable fashion.
     *
     * @return The same instance of WaveScanRecord for chaining.
     */
    public WaveScanRecord duration(Long duration) {
        this.duration = duration;
        return this;
    }

    /**
     * @return the containerImage property value
     */
    public String getContainerImage() {
        return containerImage;
    }

    /**
     * Set the containerImage property value
     *
     * @param containerImage property value to set
     */
    public void setContainerImage(String containerImage) {
        this.containerImage = containerImage;
    }

    /**
     * Set containerImage in a chainable fashion.
     *
     * @return The same instance of WaveScanRecord for chaining.
     */
    public WaveScanRecord containerImage(String containerImage) {
        this.containerImage = containerImage;
        return this;
    }

    /**
     * @return the id property value
     */
    public String getId() {
        return id;
    }

    /**
     * Set the id property value
     *
     * @param id property value to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Set id in a chainable fashion.
     *
     * @return The same instance of WaveScanRecord for chaining.
     */
    public WaveScanRecord id(String id) {
        this.id = id;
        return this;
    }

    /**
     * @return the startTime property value
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Set the startTime property value
     *
     * @param startTime property value to set
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * Set startTime in a chainable fashion.
     *
     * @return The same instance of WaveScanRecord for chaining.
     */
    public WaveScanRecord startTime(String startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * @return the status property value
     */
    public String getStatus() {
        return status;
    }

    /**
     * Set the status property value
     *
     * @param status property value to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Set status in a chainable fashion.
     *
     * @return The same instance of WaveScanRecord for chaining.
     */
    public WaveScanRecord status(String status) {
        this.status = status;
        return this;
    }

    /**
     * @return the vulnerabilities property value
     */
    public List<@Valid Vulnerability> getVulnerabilities() {
        return vulnerabilities;
    }

    /**
     * Set the vulnerabilities property value
     *
     * @param vulnerabilities property value to set
     */
    public void setVulnerabilities(List<@Valid Vulnerability> vulnerabilities) {
        this.vulnerabilities = vulnerabilities;
    }

    /**
     * Set vulnerabilities in a chainable fashion.
     *
     * @return The same instance of WaveScanRecord for chaining.
     */
    public WaveScanRecord vulnerabilities(List<@Valid Vulnerability> vulnerabilities) {
        this.vulnerabilities = vulnerabilities;
        return this;
    }
    /**
     * Add an item to the vulnerabilities property in a chainable fashion.
     *
     * @return The same instance of WaveScanRecord for chaining.
     */
    public WaveScanRecord addVulnerabilitiesItem(Vulnerability vulnerabilitiesItem) {
        vulnerabilities.add(vulnerabilitiesItem);
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var waveScanRecord = (WaveScanRecord) o;
        return Objects.equals(buildId, waveScanRecord.buildId)
            && Objects.equals(duration, waveScanRecord.duration)
            && Objects.equals(containerImage, waveScanRecord.containerImage)
            && Objects.equals(id, waveScanRecord.id)
            && Objects.equals(startTime, waveScanRecord.startTime)
            && Objects.equals(status, waveScanRecord.status)
            && Objects.equals(vulnerabilities, waveScanRecord.vulnerabilities);
    }

    @Override
    public int hashCode() {
        return Objects.hash(buildId, duration, containerImage, id, startTime, status, vulnerabilities);
    }

    @Override
    public String toString() {
        return "WaveScanRecord("
            + "buildId: " + getBuildId() + ", "
            + "duration: " + getDuration() + ", "
            + "containerImage: " + getContainerImage() + ", "
            + "id: " + getId() + ", "
            + "startTime: " + getStartTime() + ", "
            + "status: " + getStatus() + ", "
            + "vulnerabilities: " + getVulnerabilities()
            + ")";
    }

}