/*
 * Wave API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.v1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.wave.api.v1.model.WaveBuildRecordFormat;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Wave container build details
 */
@Serdeable
@JsonPropertyOrder({
    WaveBuildRecord.JSON_PROPERTY_BUILD_ID,
    WaveBuildRecord.JSON_PROPERTY_CONDA_FILE,
    WaveBuildRecord.JSON_PROPERTY_DIGEST,
    WaveBuildRecord.JSON_PROPERTY_DOCKER_FILE,
    WaveBuildRecord.JSON_PROPERTY_DURATION,
    WaveBuildRecord.JSON_PROPERTY_EXIT_STATUS,
    WaveBuildRecord.JSON_PROPERTY_FORMAT,
    WaveBuildRecord.JSON_PROPERTY_OFFSET_ID,
    WaveBuildRecord.JSON_PROPERTY_PLATFORM,
    WaveBuildRecord.JSON_PROPERTY_REQUEST_IP,
    WaveBuildRecord.JSON_PROPERTY_SCAN_ID,
    WaveBuildRecord.JSON_PROPERTY_START_TIME,
    WaveBuildRecord.JSON_PROPERTY_SUCCEEDED,
    WaveBuildRecord.JSON_PROPERTY_TARGET_IMAGE,
    WaveBuildRecord.JSON_PROPERTY_USER_EMAIL,
    WaveBuildRecord.JSON_PROPERTY_USER_ID,
    WaveBuildRecord.JSON_PROPERTY_USER_NAME,
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class WaveBuildRecord {

    public static final String JSON_PROPERTY_BUILD_ID = "buildId";
    public static final String JSON_PROPERTY_CONDA_FILE = "condaFile";
    public static final String JSON_PROPERTY_DIGEST = "digest";
    public static final String JSON_PROPERTY_DOCKER_FILE = "dockerFile";
    public static final String JSON_PROPERTY_DURATION = "duration";
    public static final String JSON_PROPERTY_EXIT_STATUS = "exitStatus";
    public static final String JSON_PROPERTY_FORMAT = "format";
    public static final String JSON_PROPERTY_OFFSET_ID = "offsetId";
    public static final String JSON_PROPERTY_PLATFORM = "platform";
    public static final String JSON_PROPERTY_REQUEST_IP = "requestIp";
    public static final String JSON_PROPERTY_SCAN_ID = "scanId";
    public static final String JSON_PROPERTY_START_TIME = "startTime";
    public static final String JSON_PROPERTY_SUCCEEDED = "succeeded";
    public static final String JSON_PROPERTY_TARGET_IMAGE = "targetImage";
    public static final String JSON_PROPERTY_USER_EMAIL = "userEmail";
    public static final String JSON_PROPERTY_USER_ID = "userId";
    public static final String JSON_PROPERTY_USER_NAME = "userName";

    @NotNull
    @JsonProperty(JSON_PROPERTY_BUILD_ID)
    private String buildId;

    @NotNull
    @JsonProperty(JSON_PROPERTY_CONDA_FILE)
    private String condaFile;

    @NotNull
    @JsonProperty(JSON_PROPERTY_DIGEST)
    private String digest;

    @NotNull
    @JsonProperty(JSON_PROPERTY_DOCKER_FILE)
    private String dockerFile;

    @NotNull
    @JsonProperty(JSON_PROPERTY_DURATION)
    private Long duration;

    @NotNull
    @JsonProperty(JSON_PROPERTY_EXIT_STATUS)
    private Integer exitStatus;

    @NotNull
    @JsonProperty(JSON_PROPERTY_FORMAT)
    private WaveBuildRecordFormat format;

    @NotNull
    @JsonProperty(JSON_PROPERTY_OFFSET_ID)
    private String offsetId;

    @NotNull
    @JsonProperty(JSON_PROPERTY_PLATFORM)
    private String platform;

    @NotNull
    @JsonProperty(JSON_PROPERTY_REQUEST_IP)
    private String requestIp;

    @NotNull
    @JsonProperty(JSON_PROPERTY_SCAN_ID)
    private String scanId;

    @NotNull
    @JsonProperty(JSON_PROPERTY_START_TIME)
    private String startTime;

    @NotNull
    @JsonProperty(JSON_PROPERTY_SUCCEEDED)
    private Boolean succeeded;

    @NotNull
    @JsonProperty(JSON_PROPERTY_TARGET_IMAGE)
    private String targetImage;

    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_EMAIL)
    private String userEmail;

    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_ID)
    private Long userId;

    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_NAME)
    private String userName;

    /**
     * @return the buildId property value
     */
    public String getBuildId() {
        return buildId;
    }

    /**
     * Set the buildId property value
     *
     * @param buildId property value to set
     */
    public void setBuildId(String buildId) {
        this.buildId = buildId;
    }

    /**
     * Set buildId in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord buildId(String buildId) {
        this.buildId = buildId;
        return this;
    }

    /**
     * @return the condaFile property value
     */
    public String getCondaFile() {
        return condaFile;
    }

    /**
     * Set the condaFile property value
     *
     * @param condaFile property value to set
     */
    public void setCondaFile(String condaFile) {
        this.condaFile = condaFile;
    }

    /**
     * Set condaFile in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord condaFile(String condaFile) {
        this.condaFile = condaFile;
        return this;
    }

    /**
     * @return the digest property value
     */
    public String getDigest() {
        return digest;
    }

    /**
     * Set the digest property value
     *
     * @param digest property value to set
     */
    public void setDigest(String digest) {
        this.digest = digest;
    }

    /**
     * Set digest in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord digest(String digest) {
        this.digest = digest;
        return this;
    }

    /**
     * @return the dockerFile property value
     */
    public String getDockerFile() {
        return dockerFile;
    }

    /**
     * Set the dockerFile property value
     *
     * @param dockerFile property value to set
     */
    public void setDockerFile(String dockerFile) {
        this.dockerFile = dockerFile;
    }

    /**
     * Set dockerFile in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord dockerFile(String dockerFile) {
        this.dockerFile = dockerFile;
        return this;
    }

    /**
     * @return the duration property value
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * Set the duration property value
     *
     * @param duration property value to set
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * Set duration in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord duration(Long duration) {
        this.duration = duration;
        return this;
    }

    /**
     * @return the exitStatus property value
     */
    public Integer getExitStatus() {
        return exitStatus;
    }

    /**
     * Set the exitStatus property value
     *
     * @param exitStatus property value to set
     */
    public void setExitStatus(Integer exitStatus) {
        this.exitStatus = exitStatus;
    }

    /**
     * Set exitStatus in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord exitStatus(Integer exitStatus) {
        this.exitStatus = exitStatus;
        return this;
    }

    /**
     * @return the format property value
     */
    public WaveBuildRecordFormat getFormat() {
        return format;
    }

    /**
     * Set the format property value
     *
     * @param format property value to set
     */
    public void setFormat(WaveBuildRecordFormat format) {
        this.format = format;
    }

    /**
     * Set format in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord format(WaveBuildRecordFormat format) {
        this.format = format;
        return this;
    }

    /**
     * @return the offsetId property value
     */
    public String getOffsetId() {
        return offsetId;
    }

    /**
     * Set the offsetId property value
     *
     * @param offsetId property value to set
     */
    public void setOffsetId(String offsetId) {
        this.offsetId = offsetId;
    }

    /**
     * Set offsetId in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord offsetId(String offsetId) {
        this.offsetId = offsetId;
        return this;
    }

    /**
     * @return the platform property value
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Set the platform property value
     *
     * @param platform property value to set
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * Set platform in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord platform(String platform) {
        this.platform = platform;
        return this;
    }

    /**
     * @return the requestIp property value
     */
    public String getRequestIp() {
        return requestIp;
    }

    /**
     * Set the requestIp property value
     *
     * @param requestIp property value to set
     */
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    /**
     * Set requestIp in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord requestIp(String requestIp) {
        this.requestIp = requestIp;
        return this;
    }

    /**
     * @return the scanId property value
     */
    public String getScanId() {
        return scanId;
    }

    /**
     * Set the scanId property value
     *
     * @param scanId property value to set
     */
    public void setScanId(String scanId) {
        this.scanId = scanId;
    }

    /**
     * Set scanId in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord scanId(String scanId) {
        this.scanId = scanId;
        return this;
    }

    /**
     * @return the startTime property value
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Set the startTime property value
     *
     * @param startTime property value to set
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * Set startTime in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord startTime(String startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * @return the succeeded property value
     */
    public Boolean getSucceeded() {
        return succeeded;
    }

    /**
     * Set the succeeded property value
     *
     * @param succeeded property value to set
     */
    public void setSucceeded(Boolean succeeded) {
        this.succeeded = succeeded;
    }

    /**
     * Set succeeded in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord succeeded(Boolean succeeded) {
        this.succeeded = succeeded;
        return this;
    }

    /**
     * @return the targetImage property value
     */
    public String getTargetImage() {
        return targetImage;
    }

    /**
     * Set the targetImage property value
     *
     * @param targetImage property value to set
     */
    public void setTargetImage(String targetImage) {
        this.targetImage = targetImage;
    }

    /**
     * Set targetImage in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord targetImage(String targetImage) {
        this.targetImage = targetImage;
        return this;
    }

    /**
     * @return the userEmail property value
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * Set the userEmail property value
     *
     * @param userEmail property value to set
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * Set userEmail in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord userEmail(String userEmail) {
        this.userEmail = userEmail;
        return this;
    }

    /**
     * @return the userId property value
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Set the userId property value
     *
     * @param userId property value to set
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Set userId in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord userId(Long userId) {
        this.userId = userId;
        return this;
    }

    /**
     * @return the userName property value
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Set the userName property value
     *
     * @param userName property value to set
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Set userName in a chainable fashion.
     *
     * @return The same instance of WaveBuildRecord for chaining.
     */
    public WaveBuildRecord userName(String userName) {
        this.userName = userName;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var waveBuildRecord = (WaveBuildRecord) o;
        return Objects.equals(buildId, waveBuildRecord.buildId)
            && Objects.equals(condaFile, waveBuildRecord.condaFile)
            && Objects.equals(digest, waveBuildRecord.digest)
            && Objects.equals(dockerFile, waveBuildRecord.dockerFile)
            && Objects.equals(duration, waveBuildRecord.duration)
            && Objects.equals(exitStatus, waveBuildRecord.exitStatus)
            && Objects.equals(format, waveBuildRecord.format)
            && Objects.equals(offsetId, waveBuildRecord.offsetId)
            && Objects.equals(platform, waveBuildRecord.platform)
            && Objects.equals(requestIp, waveBuildRecord.requestIp)
            && Objects.equals(scanId, waveBuildRecord.scanId)
            && Objects.equals(startTime, waveBuildRecord.startTime)
            && Objects.equals(succeeded, waveBuildRecord.succeeded)
            && Objects.equals(targetImage, waveBuildRecord.targetImage)
            && Objects.equals(userEmail, waveBuildRecord.userEmail)
            && Objects.equals(userId, waveBuildRecord.userId)
            && Objects.equals(userName, waveBuildRecord.userName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(buildId, condaFile, digest, dockerFile, duration, exitStatus, format, offsetId, platform, requestIp, scanId, startTime, succeeded, targetImage, userEmail, userId, userName);
    }

    @Override
    public String toString() {
        return "WaveBuildRecord("
            + "buildId: " + getBuildId() + ", "
            + "condaFile: " + getCondaFile() + ", "
            + "digest: " + getDigest() + ", "
            + "dockerFile: " + getDockerFile() + ", "
            + "duration: " + getDuration() + ", "
            + "exitStatus: " + getExitStatus() + ", "
            + "format: " + getFormat() + ", "
            + "offsetId: " + getOffsetId() + ", "
            + "platform: " + getPlatform() + ", "
            + "requestIp: " + getRequestIp() + ", "
            + "scanId: " + getScanId() + ", "
            + "startTime: " + getStartTime() + ", "
            + "succeeded: " + getSucceeded() + ", "
            + "targetImage: " + getTargetImage() + ", "
            + "userEmail: " + getUserEmail() + ", "
            + "userId: " + getUserId() + ", "
            + "userName: " + getUserName()
            + ")";
    }

}