/*
 * Wave API
 * Wave Containers Provisioning Service API A comprehensive container orchestration and build service
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.schema.v0;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import io.seqera.wave.api.schema.v0.ServiceInfo;
import com.fasterxml.jackson.annotation.*;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;
import jakarta.annotation.Generated;

/**
 * Service information response
 */
@JsonPropertyOrder(ServiceInfoResponse.JSON_PROPERTY_SERVICE_INFO)
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Introspected
public class ServiceInfoResponse {

    public static final String JSON_PROPERTY_SERVICE_INFO = "serviceInfo";

    @NotNull
    @Valid
    @JsonProperty(JSON_PROPERTY_SERVICE_INFO)
    private ServiceInfo serviceInfo;

    private ServiceInfoResponse() {
    }

    public ServiceInfoResponse(ServiceInfo serviceInfo) {
        this.serviceInfo = serviceInfo;
    }

    /**
     * @return the serviceInfo property value
     */
    public ServiceInfo getServiceInfo() {
        return serviceInfo;
    }

    /**
     * Set the serviceInfo property value
     *
     * @param serviceInfo property value to set
     */
    public void setServiceInfo(ServiceInfo serviceInfo) {
        this.serviceInfo = serviceInfo;
    }

    /**
     * Set serviceInfo in a chainable fashion.
     *
     * @return The same instance of ServiceInfoResponse for chaining.
     */
    public ServiceInfoResponse serviceInfo(ServiceInfo serviceInfo) {
        this.serviceInfo = serviceInfo;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        var serviceInfoResponse = (ServiceInfoResponse) o;
        return Objects.equals(serviceInfo, serviceInfoResponse.serviceInfo);
    }

    @Override
    public int hashCode() {
        return Objects.hash(serviceInfo);
    }

    @Override
    public String toString() {
        return "ServiceInfoResponse("
            + "serviceInfo: " + getServiceInfo()
            + ")";
    }

}