/*
 * Wave API
 * Wave Containers Provisioning Service API A comprehensive container orchestration and build service
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.spec;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import io.seqera.wave.api.schema.v0.ContainerStatusResponse;
import io.seqera.wave.api.schema.v0.ErrorResponse;
import io.micronaut.http.HttpResponse;
import io.seqera.wave.api.schema.v0.SubmitContainerTokenRequest;
import io.seqera.wave.api.schema.v0.SubmitContainerTokenResponse;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Controller
public interface ContainerApiSpec {

    /**
     * Delete container
     *
     * @param requestId (required)
     * @return There is no content to send for this request, but the headers may be useful.  (status code 204)
     *         or An unexpected error response. (status code default)
     */
    @Delete("/v1alpha1/containers/{requestId}")
    HttpResponse<Void> deleteContainer(
        @PathVariable("requestId") @NotNull String requestId
    );

    /**
     * Get container status
     *
     * @param requestId (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code default)
     */
    @Get("/v1alpha1/containers/{requestId}/status")
    ContainerStatusResponse getContainerStatus(
        @PathVariable("requestId") @NotNull String requestId
    );

    /**
     * Submit container token request (legacy)
     *
     * @param submitContainerTokenRequest (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code default)
     */
    @Post("/container")
    SubmitContainerTokenResponse submitContainerToken(
        @Body @NotNull @Valid SubmitContainerTokenRequest submitContainerTokenRequest
    );

    /**
     * Submit container token request v1
     *
     * @param submitContainerTokenRequest (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code default)
     */
    @Post("/v1alpha1/containers")
    SubmitContainerTokenResponse submitContainerTokenV1(
        @Body @NotNull @Valid SubmitContainerTokenRequest submitContainerTokenRequest
    );

    /**
     * Submit container token request v2
     *
     * @param submitContainerTokenRequest (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code default)
     */
    @Post("/v1alpha2/containers")
    SubmitContainerTokenResponse submitContainerTokenV2(
        @Body @NotNull @Valid SubmitContainerTokenRequest submitContainerTokenRequest
    );

}