/*
 * Wave API
 * Wave Containers Provisioning Service API A comprehensive container orchestration and build service
 *
 * The version of the OpenAPI document: 1.25.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.spec;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import io.seqera.wave.api.schema.v0.ErrorResponse;
import io.seqera.wave.api.schema.v0.ValidateRegistryCredsRequest;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Controller
public interface ValidateApiSpec {

    /**
     * Validate registry credentials
     *
     * @param validateRegistryCredsRequest (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code default)
     */
    @Post("/validate-creds")
    Map<String, Object> validateCredentials(
        @Body @NotNull @Valid ValidateRegistryCredsRequest validateRegistryCredsRequest
    );

}