wave:
  debug: false
  server:
    url: "https://wave.seqera.io"
  tokens:
    cache:
      duration: "36h"
  metrics:
    enabled: true
  db :
    uri : "jdbc:postgresql://localhost:5432/postgres"
    user : "postgres"
    password : "postgres"
redis:
  uri: "redis://redis:6379"
mail:
  from: "wave-app@seqera.io"
tower:
  endpoint:
    url: 'https://api.cloud.stage-seqera.io'
rate-limit:
  build:
    anonymous: 25/1d
    authenticated: 100/1h
  pull:
    anonymous: 250/1h
    authenticated: 2000/1m
  timeout-errors:
    max-rate: 100/1m
license:
  server:
    url: 'https://licenses.seqera.io'
micronaut:
  netty:
    event-loops:
      default:
        num-threads: 64
  http:
    services:
      stream-client:
        read-timeout: '30s'
        read-idle-timeout: '5m'
endpoints:
  env:
    enabled: false
  bean:
    enabled: false
  caches:
    enabled: false
  refresh:
    enabled: false
  loggers:
    enabled: false
  info:
    enabled: false
  metrics:
    enabled: true
  health:
    enabled: true
    disk-space:
      enabled: false
    jdbc:
      enabled: false
