wave:
  debug: false
  tokens:
    cache:
      duration: "36h"
  metrics:
    enabled: true
rate-limit:
  pull:
    anonymous: 250/1h
    authenticated: 2000/1m
  timeout-errors:
    max-rate: 100/1m
micronaut:
  netty:
    event-loops:
      default:
        num-threads: 64
  http:
    services:
      stream-client:
        read-timeout: '30s'
        read-idle-timeout: '5m'
endpoints:
  env:
    enabled: false
  bean:
    enabled: false
  caches:
    enabled: false
  refresh:
    enabled: false
  loggers:
    enabled: false
  info:
    enabled: false
  metrics:
    enabled: true
  health:
    enabled: true
    disk-space:
      enabled: false
    jdbc:
      enabled: false
