services:
  wave:
    image: wave-app # replace with the actual image name
    ports:
      - 9090:9090
    volumes:
      - $PWD:/work
    environment:
      - MICRONAUT_ENVIRONMENTS=lite,rate-limit,redis,prometheus
      - WAVE_JVM_OPTS=-Djdk.traceVirtualThreadInThreadDump=full -XX:InitialRAMPercentage=65 -XX:MaxRAMPercentage=65 -XX:+HeapDumpOnOutOfMemoryError -XX:MaxDirectMemorySize=200m -Dio.netty.maxDirectMemory=0 -Djdk.httpclient.keepalive.timeout=10 -Djdk.tracePinnedThreads=short
      - REDIS_URI=redis://redis:6379
    working_dir: /work
