/*
 * Wave API
 * Wave Containers Provisioning Service API A comprehensive container orchestration and build service
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.seqera.wave.api.spec.v1;

import io.micronaut.http.annotation.*;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.core.convert.format.Format;
import io.seqera.wave.api.schema.v1.BuildStatusResponse;
import io.seqera.wave.api.schema.v1.ErrorResponse;
import jakarta.annotation.Generated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;

@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Controller
public interface BuildApiSpec {

    /**
     * Get build record
     *
     * @param buildId (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code default)
     */
    @Get("/v1alpha1/builds/{buildId}")
    Map<String, Object> getBuild(
        @PathVariable("buildId") @NotNull String buildId
    );

    /**
     * Get build logs
     *
     * @param buildId (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code default)
     */
    @Get("/v1alpha1/builds/{buildId}/logs")
    String getBuildLogs(
        @PathVariable("buildId") @NotNull String buildId
    );

    /**
     * Get build status
     *
     * @param buildId (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code default)
     */
    @Get("/v1alpha1/builds/{buildId}/status")
    BuildStatusResponse getBuildStatus(
        @PathVariable("buildId") @NotNull String buildId
    );

    /**
     * Get conda lock file
     *
     * @param buildId (required)
     * @return The request has succeeded. (status code 200)
     *         or An unexpected error response. (status code default)
     */
    @Get("/v1alpha1/builds/{buildId}/condalock")
    String getCondaLock(
        @PathVariable("buildId") @NotNull String buildId
    );

}