FROM {{pixi_image}} AS build

COPY conda.yml /opt/wave/pixi.lock
WORKDIR /opt/wave
RUN {{manifest_generate}}
    && pixi install --frozen \
    && mkdir -p /root/.pixi/bin \
    {{base_packages}}
    && pixi shell-hook > /shell-hook.sh \
    && echo 'exec "$@"' >> /shell-hook.sh \
    && echo ">> CONDA_LOCK_START" \
    && cat /opt/wave/pixi.lock \
    && echo "<< CONDA_LOCK_END"

FROM {{base_image}} AS final

COPY --from=build /opt/wave/.pixi/envs/default /opt/wave/.pixi/envs/default
COPY --from=build /root/.pixi /root/.pixi
COPY --from=build /shell-hook.sh /shell-hook.sh

USER root
ENV USER=root
ENV PATH=/root/.pixi/bin:$PATH

ENTRYPOINT ["/bin/bash", "/shell-hook.sh"]
CMD ["/bin/bash"]
