FROM {{pixi_image}} AS build

COPY conda.yml /opt/wave/pixi.toml
WORKDIR /opt/wave
RUN pixi install \
    && pixi shell-hook > /shell-hook.sh \
    && echo 'exec "$@"' >> /shell-hook.sh \
    && echo ">> PIXI_LOCK_START" \
    && cat /opt/wave/pixi.lock \
    && echo "<< PIXI_LOCK_END"

FROM {{base_image}} AS final

COPY --from=build /opt/wave/.pixi/envs/default /opt/wave/.pixi/envs/default
COPY --from=build /shell-hook.sh /shell-hook.sh

USER root
ENV USER=root

ENTRYPOINT ["/bin/bash", "/shell-hook.sh"]
CMD ["/bin/bash"]
