name: Build and publish Singularity container image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version (e.g., 4.2.1-r4)'
        required: true
        default: '4.2.1-r4'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: public.cr.seqera.io
          username: ${{ vars.SEQERA_PUBLIC_CR_USERNAME  }}
          password: ${{ secrets.SEQERA_PUBLIC_CR_PASSWORD }}

      - name: Build and Push Image to public.cr.seqera.io
        run: |
          cd singularity
          make build version=${{ github.event.inputs.version }}
