name: Build and publish ZeroFS container image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version (e.g., 0.1.0)'
        required: true
      zfsversion :
        description : 'add the latest version of zerofs  https://github.com/Barre/ZeroFS/releases (e.g., 0.15.4)'
        required : true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: public.cr.seqera.io
          username: ${{ vars.SEQERA_PUBLIC_CR_USERNAME  }}
          password: ${{ secrets.SEQERA_PUBLIC_CR_PASSWORD }}

      - name: Build and Push Image to public.cr.seqera.io
        run: |
          cd zerofs
          make build version=${{ github.event.inputs.version }} zfs_version=${{ github.event.inputs.zfsversion }}
