name: Generate and submit dependency graph for wave
on:
    push:
      branches:
        - '**'

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Generate and submit dependency graph for wave
      uses: gradle/actions/dependency-submission@v4
      with:
        dependency-resolution-task: "dependencies"
        additional-arguments: "--configuration runtimeClasspath"
        dependency-graph: generate-and-submit
