FROM {{mamba_image}}:2.1.1 AS build
RUN \
    micromamba install -y -n base {{channel_opts}} {{target}} \
    {{base_packages}}
    && micromamba env export --name base --explicit > environment.lock \
    && echo ">> CONDA_LOCK_START" \
    && cat environment.lock \
    && echo "<< CONDA_LOCK_END"

FROM {{base_image}} AS prod
ARG MAMBA_ROOT_PREFIX="/opt/conda"
ENV MAMBA_ROOT_PREFIX=$MAMBA_ROOT_PREFIX
COPY --from=build "$MAMBA_ROOT_PREFIX" "$MAMBA_ROOT_PREFIX"
USER root
ENV PATH="$MAMBA_ROOT_PREFIX/bin:$PATH"
